### ISSUE TITLE
Cache directory for HXL Proxy

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/hxl-proxy#100]
The head of the dev branch for the HXL Proxy now uses a disk-based cache rather than a memory-based cache, so there are new config options (and possibly new Docker requirements) for deploying the proxy.

Please advised that you're ready (and don't see any problems), before I move this change to the master branch.

**Details**

The config.py file can now use the following fields to control caching (see config.py.TEMPLATE):

    CACHE_DIR = '/tmp'
    CACHE_MAX_ITEMS = 1000
    CACHE_DEFAULT_TIMEOUT_SECONDS = 3600 # 1 hour

/tmp/ isn't a great choice, so that should be set to somewhere else.  Soon, the HXL Proxy will be using the cache for input as well as output (to avoid hitting an external source over and over).  

Also TBD: should we move to a 24-hour caching time? Most of our data isn't very fast-changing. We can create a new issue for this when the time is right.

**Comment by teodorescuserban** [comment]
Hmh we should talk about this a bit.

On Mon, 2 May 2016, 23:21 David Megginson, <notifications@github.com> wrote:

> Assigned #100 <https://github.com/HXLStandard/hxl-proxy/issues/100> to
> @teodorescuserban <https://github.com/teodorescuserban>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/HXLStandard/hxl-proxy/issues/100#event-648072609>
>
-- 
Serban Teodorescu
SysEngineer / DevOps

**Comment by davidmegginson** [comment]
@teodorescuserban - let me know a good time to talk.

**Comment by davidmegginson** [comment]
@teodorescuserban - The beta version of the proxy is now using a disk-based cache -- take a look at /srv/www/hxl-proxy/beta/local/config.py to see how it's set up.

**Comment by davidmegginson** [comment]
Resolved with the prod rollout in September 2016.
