### ISSUE TITLE
Cache becomes sticky

### ISSUE THREAD

**Issue by SimonbJohnson** [HXLStandard/hxl-proxy#101]
Occasionally if I update a dataset and run a force=1 in a short timeframe (sub one hour) the returned data will be any one of the previous caches seemingly at random.  Happened last on this url (which is now functioning properly)

https://proxy.hxlstandard.org/data.json?strip-headers=on&url=https%3A//docs.google.com/spreadsheets/d/1uQBqfqxqqEYbueJFJg9coqViRlBWK9aAeSeBvuzbEGM/edit%23gid%3D0

**Comment by davidmegginson** [comment]
@SimonbJohnson -- I've just done a major overhaul of the caching system on the beta version of the proxy (not yet in prod yet). Could you test it and let me know if the problem happens there as well?

**Comment by SimonbJohnson** [comment]
@davidmegginson, I will do some testing this week!

**Comment by davidmegginson** [comment]
With the new version of the Proxy deployed to production, the Proxy is now caching input as well as output, and I don't think the input is respecting the "Never cache" flag. I'll work on that under this issue.

**Comment by SimonbJohnson** [comment]
Yes, I'm seeing the input getting cached. I updated a spreadsheet and with force=on was showing the old data. I tried adding new get parameters with same result.  Went back to HXL proxy website and loaded spreadsheet again and saw new data while the other link was still showing the old data.

**Comment by davidmegginson** [comment]
Fixed with #122
