### ISSUE TITLE
Error - In machine-speak:  No HXL hashtags found

### ISSUE THREAD

**Issue by siemvaessen** [HXLStandard/hxl-proxy#116]
URI: https://beta.proxy.hxlstandard.org/data/edit?url=https%3A%2F%2Fdata.hdx.rwlabs.org%2Fdataset%2F4502ef36-7039-4d7d-adf4-e061720cd59c%2Fresource%2Fe8fbd983-97ac-4d4f-bc98-768418057b9d

Something went wrong!

Details

In machine-speak:

No HXL hashtags found

**Comment by danmihaila** [comment]
Can you check this url:

https://proxy.hxlstandard.org/data/tagger?url=https%3A//data.hdx.rwlabs.org/dataset/4502ef36-7039-4d7d-adf4-e061720cd59c/resource/e8fbd983-97ac-4d4f-bc98-768418057b9d


Dan Mihaila

**Comment by davidmegginson** [comment]
It's not a HXL-ated dataset, so the proxy starts by providing a simple UI
to add hashtags.  Is that what you're seeing?

D

**Comment by davidmegginson** [comment]
There seems to be a deployment problem with the beta version of the HXL Proxy, where it's not automatically redirecting to the tagger.  The production version (see Dan's link above) works properly, as does the local dev copy on my laptop. I'll try redeploying the beta this afternoon, and close the issue if all is well.

**Comment by davidmegginson** [comment]
Deployment problem in beta fixed (some files were owned by root and not being updated)  -- it now behaves as expected (see the original link at the top of the issue).  Thanks to @siemvaessen for the bug report.
