### ISSUE TITLE
Pass filename as get param for output file

### ISSUE THREAD

**Issue by SimonbJohnson** [HXLStandard/hxl-proxy#121]
Currently all the file names are data.csv.  In my download folder I have many files of the form data(yy).csv.  Being able to pass the filename will add more context to them.

**Comment by davidmegginson** [comment]
This is currently possible for a saved recipe, using the "Basename for download" field (the param is named "stub" internally).  Here's an example:

https://beta.proxy.hxlstandard.org/data/EZwnGi

You'll see here that the data download files are sample-data.csv and sample-data.json 

It should be possible to add this for non-saved recipes as well (where all the params are in the GET request).  I'll look into it.

**Comment by davidmegginson** [comment]
Implemented.  There is now an option to enter the base filename ("stub") parameter without saving the recipe to a short URL.

Note that the download will accept anything after /data/download/, as long as it has a .csv or .json extension. The stub simply controls the default for the download links on the main data view page.

**Comment by davidmegginson** [comment]
Sample link with the _stub_ parameter: https://beta.proxy.hxlstandard.org/data?filter_count=7&stub=foo&format=html&url=https%3A//docs.google.com/spreadsheets/d/1ytPD-f4a8CbNKTfMS3EqZOpBo9LWCk_NDKxJCgmpXA8/edit%23gid%3D1101521524

**Comment by SimonbJohnson** [comment]
When trying to add a select filter and clicking update it won't progress citing that the filename has not been filled in

<img width="1273" alt="screen shot 2016-10-18 at 12 07 00" src="https://cloud.githubusercontent.com/assets/2110742/19475366/a75a0bea-952b-11e6-99e0-d4f29c135bcd.png">

**Comment by davidmegginson** [comment]
Must be a copy/paste error in the HTML5 form. I'll look at it today.
