### ISSUE TITLE
User able to set caching timeout

### ISSUE THREAD

**Issue by SimonbJohnson** [HXLStandard/hxl-proxy#122]
I have a source that updates hourly, so currently force a no cache.  Could reduce server load, by being able to pass in a cache timeout in params

**Comment by davidmegginson** [comment]
Configuring to skip the input cache (as well as output) if &force=on ; however, doing so does _not_ update the input cache as well.

**Comment by davidmegginson** [comment]
Deployed to https://beta.proxy.hxlstandard.org and tested successfully.

Will be deployed to prod on next rollout.
