### ISSUE TITLE
Filter: add column error

### ISSUE THREAD

**Issue by danmihaila** [HXLStandard/hxl-proxy#128]
How to reproduce
1. Choose add column filter
2. don't add anything at the "fixed value"
3. click update
4. error page (expecting string...)
5. return to previous page it will not allow you to change anything for filters, can not remove the current filter, etc.

**Comment by davidmegginson** [comment]
Two options for fixing:
1. Require the fixed value in HTML5 form validation, to avoid this problem (most of the time).
2. Make the proxy accept a blank fixed value (e.g. for inserting a blank column).

I'm leaning to the second option.

**Comment by davidmegginson** [comment]
Tested:
1. Choose add column filter
2. don't add anything at the "fixed value"
3. click update
4. error page (expecting string...)
_Confirmed to this point._
5. return to previous page it will not allow you to change anything for filters, can not remove the current filter, etc.
_If I open the filter and fill in the "Fixed value" field, I'm able to continue._

**Comment by davidmegginson** [comment]
Deployed to beta. Here's an example where the fixed value was left blank: https://beta.proxy.hxlstandard.org/data/edit?filter01=add&strip-headers=on&strip-headers=on&filter_count=7&format=html&filter01=add&url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1ytPD-f4a8CbNKTfMS3EqZOpBo9LWCk_NDKxJCgmpXA8%2Fedit%23gid%3D1101521524&add-tag01=%23foo
