### ISSUE TITLE
Get headers from a #hxl file & limit/pagination

### ISSUE THREAD

**Issue by danmihaila** [HXLStandard/hxl-proxy#134]
1. Api call to get the headers of a #hxl file
 - columns name
 - hxl tags
2. limit the output returned by hxl proxy (in case of a big file)
 - number of rows 
 - pagination

**Comment by davidmegginson** [comment]
Added a &max_rows parameter that limits the maximum number of rows, both for preview and for download.  Example:

https://beta.proxy.hxlstandard.org/data/edit?max_rows=1&url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1ytPD-f4a8CbNKTfMS3EqZOpBo9LWCk_NDKxJCgmpXA8%2Fedit%23gid%3D1101521524

Use &max_rows=0 to see just the headers and hashtags.
