### ISSUE TITLE
Self certified server being blocked

### ISSUE THREAD

**Issue by SimonbJohnson** [HXLStandard/hxl-proxy#159]
https://proxy.hxlstandard.org/data/edit?url=https%3A%2F%2F52.91.94.199%2Fopen%2Ffieldreports%2F7

**Comment by davidmegginson** [comment]
Info for resolving here: http://stackoverflow.com/questions/30405867/how-to-get-python-requests-to-trust-a-self-signed-ssl-certificate

**Comment by davidmegginson** [comment]
Added support to libhxl-python in https://github.com/HXLStandard/libhxl-python/issues/82

**Comment by davidmegginson** [comment]
Deployed to beta and tested with @SimonbJohnson 's URL:

https://beta.proxy.hxlstandard.org/data/edit?url=https%3A%2F%2F52.91.94.199%2Fopen%2Ffieldreports%2F7&verify=off

Will push to production in next rollout.
