### ISSUE TITLE
Allow more flexible caching

### ISSUE THREAD

**Issue by SimonbJohnson** [HXLStandard/hxl-proxy#163]
It would be great to have more control over the caching on the server.  I have one call that I wish to only update when &force=on is called.  The underlying source is quite fragile, so I would like to have a check in place before updating.

**Comment by davidmegginson** [comment]
I'd like to add to this that @force=on should always update the cache (for later users).

**Comment by davidmegginson** [comment]
Moved to https://humanitarian.atlassian.net/browse/HXL-9

**Comment by davidmegginson** [comment]
Reopening, since we're managing issues on GitHub for now.

**Comment by davidmegginson** [comment]
Won't do
