### ISSUE TITLE
Error when loading file from HDX [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

### ISSUE THREAD

**Issue by bohurkmans** [HXLStandard/hxl-proxy#169]
https://proxy.hxlstandard.org/data/edit?url=https%3A%2F%2Fdata.hdx.rwlabs.org%2Fdataset%2F79165904-0ed0-417b-a743-6e7605b36d9a%2Fresource%2Fe6d5a229-92d2-4f76-9a0b-2f26854e1012

Something went wrong!

Details

In machine-speak:

[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

**Comment by danmihaila** [comment]
@bohurkmans thank you for your feedback. You are using the old url (data.hdx.rwlabs.org) for resource download. We moved to a new domain (data.humdata.org). Please use this url instead:
https://proxy.hxlstandard.org/data/edit?url=https%3A%2F%2Fdata.humdata.org%2Fdataset%2F79165904-0ed0-417b-a743-6e7605b36d9a%2Fresource%2Fe6d5a229-92d2-4f76-9a0b-2f26854e1012

**Comment by bohurkmans** [comment]
Thanks @danmihaila, that makes sense. I did not enter the URL manually though, it came up when selecting my data source through from the cloud -> HDX.

**Comment by davidmegginson** [comment]
Thanks, Bo - you've spotted a bug in the chooser. I will update it in the next couple of days, though it might take slightly longer to roll out to the production site.

**Comment by davidmegginson** [comment]
Deployed fix to https://beta.proxy.hxlstandard.org

Successfully tested workflow leading from HDX chooser to this result: https://beta.proxy.hxlstandard.org/data?url=https%3A//data.humdata.org/dataset/e2d5566d-d755-40dd-a63f-d4d298a9df1d/resource/eb99f439-ef14-4a42-b77c-4c3051d577d7

@bohurkmans - could you verify if the bug disappears for you now when you use the beta version of the Proxy?  Thanks again for your report.

**Comment by bohurkmans** [comment]
Thanks David, works as expected now!
