### ISSUE TITLE
Type of response in case of json request

### ISSUE THREAD

**Issue by alexandru-m-g** [HXLStandard/hxl-proxy#170]
I have a json request that gives a 500 Internal Server Error.

Would it be possible for the error response to:

1.  Be in json format (not HTML) to be easily parsed in javascript/browser ?
2.  Include the _Access-Control-Allow-Origin_ header ? Otherwise the browser won't allow access to the response

[Example request](https://proxy.hxlstandard.org/data.json?url=https%3A%2F%2Ftest-data.humdata.org%2Fdataset%2Fa1059d04-5ba8-4903-ad37-84621965dffb%2Fresource%2Fea75ca82-6418-4277-960b-1f03f649c8bc%2Fdownload%2Fzika-cases-tracker-copy-from-excel-data.csv&recipe=%5B%7B%22filter%22%3A%22clean_data%22%2C%22date%22%3A%22%23date%2Btracker%2Bupdate%22%7D%2C%7B%22filter%22%3A%22sort%22%2C%22tags%22%3A%22%23date%2Btracker%2Bupdate%22%7D%2C%7B%22filter%22%3A%22count%22%2C%22patterns%22%3A%5B%22%23date%2Btracker%2Bupdate%22%5D%2C%22aggregators%22%3A%5B%22sum(%23population%2Btotal)%22%5D%7D%2C%7B%22filter%22%3A%22rename_columns%22%2C%22specs%22%3A%22%23meta%2Bsum%3A%23population%2Btotal%22%7D%5D)

**Comment by alexandru-m-g** [comment]
I was thinking to show the user a more detailed error message of what went wrong (or at least log it to the console). Right now, I'm just showing an "error while retrieving data" when there's a 500 error. This is good enough for now so it's not a priority.

**Comment by davidmegginson** [comment]
Fixed and deployed to the beta version of the proxy ([live example](https://beta.proxy.hxlstandard.org/data.json?url=http%3A%2F%2Fexample.org%2Ffoo.csv)). A failure to retrieve a CSV or JSON resource will result in a JSON error structure with a CORS header, like this:

```
{
    "error": "HTTPError",
    "source_message": "<!doctype html>\n<html>\n<head>\n    <title>Example Domain</title>\n\n    <meta charset=\"utf-8\" />\n    <meta http-equiv=\"Content-type\" content=\"text/html; charset=utf-8\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n    <style type=\"text/css\">\n    body {\n        background-color: #f0f0f2;\n        margin: 0;\n        padding: 0;\n        font-family: \"Open Sans\", \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n        \n    }\n    div {\n        width: 600px;\n        margin: 5em auto;\n        padding: 50px;\n        background-color: #fff;\n        border-radius: 1em;\n    }\n    a:link, a:visited {\n        color: #38488f;\n        text-decoration: none;\n    }\n    @media (max-width: 700px) {\n        body {\n            background-color: #fff;\n        }\n        div {\n            width: auto;\n            margin: 0 auto;\n            border-radius: 0;\n            padding: 1em;\n        }\n    }\n    </style>    \n</head>\n\n<body>\n<div>\n    <h1>Example Domain</h1>\n    <p>This domain is established to be used for illustrative examples in documents. You may use this\n    domain in examples without prior coordination or asking for permission.</p>\n    <p><a href=\"http://www.iana.org/domains/example\">More information...</a></p>\n</div>\n</body>\n</html>\n",
    "source_status_code": 404,
    "source_url": "http://example.org/foo.csv"
}
```
Not all properties will be available with every error, but "error" will always be present (and "message", if the exception provides it). The HTTP status code will be 403 for something that looks like an HTTP problem with the source URL, or 500 for anything else.

@alexandru-m-g - please test before I merge into the next production release.

**Comment by alexandru-m-g** [comment]
This is really helful. I tested this a bit and it looks good to me!

**Comment by davidmegginson** [comment]
@alexandru-m-g somehow there was a regression on this issue. I've fixed it in the beta Proxy, and the fix will roll out to prod again at the end of April

**Comment by davidmegginson** [comment]
Confirmation link: https://beta.proxy.hxlstandard.org/data.json?url=http%3A%2F%2Fexample.org%2Fxxx

**Comment by alexandru-m-g** [comment]
@davidmegginson This seems to be fixed on the data.json endpoint BUT there is a similar problem on the  **validate.json** endpoint.

Here is an example: https://beta.proxy.hxlstandard.org/data/validate.json?&url=https%3A%2F%2Ffeature-data.humdata.org%2Fdataset%2F9c7035b9-bfae-4da8-8446-a92d2fcd3b50%2Fresource%2Fd83dc255-55ab-4ea2-a222-bddc591ff7ad%2Fdownload%2Fhno-nigeria-2018.xls&schema_url=https%3A%2F%2Fraw.githubusercontent.com%2FOCHA-DAP%2Ftools-datacheck-validation%2Fprod%2Fbasic-validation-schema.json
