### ISSUE TITLE
[enhancement] CSV data separated by semicolons is not understood

### ISSUE THREAD

**Issue by tinok** [HXLStandard/hxl-proxy#178]
When importing a CSV file the expected format doesn't allow fields separated by semicolons (which results in every table header being considered one single column. As a user I would like to be able to use such a file and have hxl-proxy detect the separator or allow me to specify it.

![image](https://user-images.githubusercontent.com/673511/35297380-ba61fdb4-004c-11e8-9e2c-269b51e654a9.png)

**Comment by davidmegginson** [comment]
Thanks for the report. This probably won't make it into release 1.5 this month, but I can probably add it to 1.6 next month.

**Comment by davidmegginson** [comment]
Is this a major blocker for you right now, @tinok ?

**Comment by tinok** [comment]
Thanks @davidmegginson. This is not a blocker because data imports from XLSX work fine.

**Comment by davidmegginson** [comment]
Resolved by HXLStandard/libhxl-python#159 — rolling out to production on 3 July.
