### ISSUE TITLE
Editing tag of saved project results in 404 error

### ISSUE THREAD

**Issue by tinok** [HXLStandard/hxl-proxy#181]
To reproduce: 

1. Create new project, go through all steps and save it
2. Go back to the Tags page, edit one of the tags (optional), and click on Next below the tag fields

Expected: Tags are saved and the Recipe page is opened
Instead: 404 error is shown:
![image](https://user-images.githubusercontent.com/673511/35685270-39a2b744-0737-11e8-9c3a-2000e18453cd.png)

(From David:)

- [x] attempt to reproduce error
- [x] add unit test to trigger error
- [x] implement fix
- [x] deploy to test branch and beta Proxy

**Comment by davidmegginson** [comment]
Saved recipe to use for testing: https://beta.proxy.hxlstandard.org/data/f55be1

**Comment by davidmegginson** [comment]
The bug was in the template, not the controller--url_for accidentally quoted. Fixed in dev; will deploy to beta.

**Comment by davidmegginson** [comment]
Confirmed fixed in beta.
