### ISSUE TITLE
Live Demo page is throwing an error

### ISSUE THREAD

**Issue by motrippy** [HXLStandard/hxl-proxy#182]
Hello!
I was reading through the HXL wiki and ran into an error page when i clicked the link for a live demo of the view page https://proxy.hxlstandard.org/data?select-query04-01=affected%3E100&rename-header03=Number+of+people+affected&filter01=explode&rename-header02=Year&tagger-default-tag=%23affected%2Blabel&rename-oldtag03=affected%2Bvalue&filter03=rename&url=https%3A//data.hdx.rwlabs.org/dataset/d1154122-e7c1-4623-9313-bdf358ebb32b/resource/a7268861-3c49-43d5-8e5e-dd07112e3f4a&filter02=rename&filter04=select&header-row=1&explode-header-att01=header&explode-value-att01=value&tagger-01-header=country+code&tagger-02-tag=%23country%2Bname&rename-oldtag02=affected%2Bheader&rename-newtag02=date%2Byear&tagger-01-tag=%23country%2Bcode&tagger-match-all=on&tagger-02-header=country+name&rename-newtag03=affected

error says:

> Something went wrong!
> Details
> In machine-speak:
> 
> HTTPSConnectionPool(host='data.hdx.rwlabs.org', port=443): Max retries exceeded with url: /api/3/action/resource_show?id=a7268861-3c49-43d5-8e5e-dd07112e3f4a (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f430edd80b8>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
> If you cannot resolve the problem, please help us make the HXL Proxy better! Report this bug at GitHub (and include the URL).

**Comment by davidmegginson** [comment]
Thanks for the report—I see that's still using the old HDX URL for the underlying dataset, triggering an SSL error. I'll go through the wiki and update links later today.

**Comment by davidmegginson** [comment]
Replaced obsolete domain name data.hdx.rwlabs.org with data.humdata.org for examples throughout the wiki. The live example on the View page now works again:

https://github.com/HXLStandard/hxl-proxy/wiki/View-page
