### ISSUE TITLE
Issue in Count filter when columns have a similar name

### ISSUE THREAD

**Issue by alexandru-m-g** [HXLStandard/hxl-proxy#185]
I have a file that has 2 very similar value columns: #value+funding+total+usd and #value+funding+total ( notice just "+usd" is different). 

I use a count rows filter where I group by #date+year and have 2 aggregators: sum(#value+funding+total+usd) and sum(#value+funding+total+usd)

The 2 resulting summed up columns have **the same values**.

What I get is:

#date+year | #value+funding+total | #value+funding+total+usd
-- | -- | --
(empty)  | 135540212 | 135540212
2016 | 15948786 | 15948786
2017 | 106404066 | 106404066
2018 | 147549201 | 147549201

Instead of:

#date+year | #value+funding+total | #value+funding+total+usd
-- | -- | --
(empty) | 135540212 | 169163578
2016 | 15948786 | 14338845
2017 | 106404066 | 36107198
2018 | 147549201 | 119188125

Here is the link : https://proxy.hxlstandard.org/data/edit?filter01=count&count-tags01=%23date%2Byear&count-type01-01=sum&count-pattern01-01=%23value%2Bfunding%2Btotal&count-header01-01=Count&count-column01-01=%23value%2Bfunding%2Btotal&count-type01-02=sum&count-pattern01-02=%23value%2Bfunding%2Btotal%2Busd&count-header01-02=Sum&count-column01-02=%23value%2Bfunding%2Btotal%2Busd&url=https%3A%2F%2Ftest-data.humdata.org%2Fdataset%2F8f3ec2df-ab7a-4ce1-aac1-08ec6aea38c0%2Fresource%2F77ee524c-d02a-4972-9dca-3dff973334a4%2Fdownload%2Ffts_funding_syr.csv

**Comment by davidmegginson** [comment]
This is a deliberate feature in the HXL Proxy. A hashtag pattern will ignore any attributes not in it, unless you specifically excluding them using "-", so the pattern _#value+funding+total_ is matching "#value+funding+total+usd". You could exclude it with the pattern _#value+funding+total-usd_

Details here: https://github.com/HXLStandard/hxl-proxy/wiki/Tag-patterns
