### ISSUE TITLE
Update forms to allow wildcard tag patterns

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/hxl-proxy#200]
See HXLStandard/libhxl-python#128 for details

**Comment by davidmegginson** [comment]
Updated and deployed to beta

Validation link: https://beta.proxy.hxlstandard.org/data/edit?filter01=select&select-query01-01=*%3DCOL&url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1ytPD-f4a8CbNKTfMS3EqZOpBo9LWCk_NDKxJCgmpXA8%2Fedit%23gid%3D1101521524

CC @danmihaila

**Comment by danmihaila** [comment]
working good!
