### ISSUE TITLE
changing schema second time is not working

### ISSUE THREAD

**Issue by danmihaila** [HXLStandard/hxl-proxy#201]
1. add a data source
2. go to "validate"
3. add a schema - all good.
4. change schema again with another file -> not working well. The old schema is also in url and not applied.

**Comment by davidmegginson** [comment]
Confirmed that the validation page duplicates _url_ and _schema_url_ parameters.

@danmihaila - since this is a UI-only issue that doesn't affect the sprint directly (unless the HXL Proxy ends up being the UI :) ), is it safe to leave resolution for next week, or even early next month?

**Comment by danmihaila** [comment]
sure, low priority. it will be interesting for dev team to tackle this one :)

**Comment by davidmegginson** [comment]
Fixed in c47231bab3
Deployed and tested on beta
