### ISSUE TITLE
pcodes service generate empty file for itos

### ISSUE THREAD

**Issue by danmihaila** [HXLStandard/hxl-proxy#205]
If adm4 doesn't exist for ITOS for Guinea, the pcodes service of hxl proxy will generate an empty csv file which crashes the validation
https://beta.proxy.hxlstandard.org/data/validate?url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F19oLyom0jNYSZJKXgbPKEVYbdlv8zIAuGGRYJAYttOb0%2Fedit%23gid%3D0&schema_url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1EyUzGO7M2juKyVuY2p1nPcxM29SauV1kT2vjRBnS9wU%2Fedit%23gid%3D1513801580&url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F19oLyom0jNYSZJKXgbPKEVYbdlv8zIAuGGRYJAYttOb0%2Fedit%23gid%3D0

<img width="866" alt="screen shot 2018-04-24 at 12 23 13" src="https://user-images.githubusercontent.com/3865844/39181556-52d7667e-47ba-11e8-842d-2dccdbefdbbf.png">

**Comment by davidmegginson** [comment]
The iTOS API is sometimes returning data for a level with no P-codes available, e.g.

http://gistmaps.itos.uga.edu/arcgis/rest/services/COD_External/GIN_pcode/MapServer/5/query?where=1%3D1&outFields=*&returnGeometry=false&f=pjson

I'm not sure if it was doing that before, but I didn't encounter it in my testing. Will update to return an error even if iTOS returns a valid result that happens to have no P-codes in it.

**Comment by davidmegginson** [comment]
Created a test case to reproduce the error, then patched the code to handle the special case from iTOS.

Merged to test and deployed to beta. Bug is fixed.

Confirmation link: https://beta.proxy.hxlstandard.org/pcodes/gin-adm4.csv

**Comment by davidmegginson** [comment]
@danmihaila - please verify and close if resolved

**Comment by danmihaila** [comment]
it is better now, but if I am adding a rule in validation schema to use adm4 for Guinea
https://beta.proxy.hxlstandard.org/data/validate?url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F19oLyom0jNYSZJKXgbPKEVYbdlv8zIAuGGRYJAYttOb0%2Fedit%23gid%3D0&schema_url=https%3A%2F%2Fraw.githubusercontent.com%2FOCHA-DAP%2Ftools-datacheck-validation%2Fmaster%2Fvalidation-schema-gin.json
it will fail
<img width="1280" alt="screen shot 2018-04-25 at 09 55 57" src="https://user-images.githubusercontent.com/3865844/39232843-e1b3c95a-486e-11e8-8bc3-5c107efb091c.png">
Can we ignore errors like this? not sure if it is a good thing if we ignore, but it will help writing general validation schema for different countries.
e.g. https://github.com/OCHA-DAP/tools-datacheck-validation/blob/master/validation-schema_pcodes.json .In this template, I expect a script to add the ISO code for country and run the validation if it finds the admX on ITOS.
what do you think?

**Comment by davidmegginson** [comment]
Currently, the Proxy is designed only to validate against datasets that actually exist. The trouble with ignoring a 404 is that people might think their data was valid, when actually, the validation taxonomy was temporarily unavailable. I can change the error a bit to say that the taxonomy was unavailable, if that helps.

We need a list of what P-codes are actually available from iTOS, and then work from that. CJ shared this link earlier:

https://data.humdata.org/cod

Will tackle in this task: HXLStandard/libhxl-python#137

**Comment by davidmegginson** [comment]
The beta Proxy will now report a single validation error when it can't load allowed values from an external source, then continue with the rest of the validation:

Confirmation link: https://beta.proxy.hxlstandard.org/data/validate?url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1X0eS8mVIeAeEcYbIUusZEgN_w-7FEGZgu6SyiUxutt0%2Fedit%23gid%3D0&schema_url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1X0eS8mVIeAeEcYbIUusZEgN_w-7FEGZgu6SyiUxutt0%2Fedit%23gid%3D2093293254&url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1X0eS8mVIeAeEcYbIUusZEgN_w-7FEGZgu6SyiUxutt0%2Fedit%23gid%3D0

**Comment by davidmegginson** [comment]
@danmihaila can you review and close the issue if this resolution is adequate for now? Understood that there's a bigger issue around figuring out in advance what's available from the iTOS service.

**Comment by danmihaila** [comment]
yes, we need to understand how to figure out what it is available on iTOS

**Comment by davidmegginson** [comment]
@danmihaila  Is that a separate issue for Data Check, and if so, is it OK to close this one?

**Comment by danmihaila** [comment]
sure, closing this one.
