### ISSUE TITLE
highlight the row with issue

### ISSUE THREAD

**Issue by danmihaila** [HXLStandard/hxl-proxy#209]
When going to a specific line
https://beta.proxy.hxlstandard.org/data?url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F18bUp-oZKtNatP6c7jZxbE52Z5BGwJTOrwa3MIWAlt_g%2Fedit%23gid%3D0&schema_url=https%3A%2F%2Fraw.githubusercontent.com%2FOCHA-DAP%2Ftools-datacheck-validation%2Fmaster%2Fvalidation-schema-gin.json&details=E4DofT8s#row_1
and might be in the middle of the file you could get lost without a numbering on the left or highlighting the row with problem.
It will be a nice feature to have, low priority.

**Comment by davidmegginson** [comment]
Moved to https://humanitarian.atlassian.net/browse/HXL-8

**Comment by davidmegginson** [comment]
Added as part of #254
