### ISSUE TITLE
Accept a validation schema as a GET/POST param

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/hxl-proxy#212]
(Originally added in error to HXLStandard/libhxl-python#126, but it doesn't belong there)

Accept a (JSON-only?) schema inline as a GET or POST param. Pass on to libhxl-python once parsed.

Requested by @danmihaila

**Comment by davidmegginson** [comment]
This feature will allow Data Check to send a custom schema, rather than serving it out via a URL.

**Comment by danmihaila** [comment]
@davidmegginson we should have all three options:
- send schema via url (like it is working now)
- send schema content (as JSON) as get param 
- post schema content (as JSON)

thanks!

**Comment by davidmegginson** [comment]
@danmihaila - I am working on the assumption that even if the schema is POSTed, all the other params will still be GET. Let me know if that's an issue for the dev team.

**Comment by davidmegginson** [comment]
Upgrading in beta caused a bug, because the beta environment bumped to flask 1.x behind the scenes, breaking the flash_cache package. Forced the Proxy to use flask 0.12.4 until we can resolve that.

**Comment by davidmegginson** [comment]
Unit tests added for GET and POST.

Working in beta. Confirmation link: https://beta.proxy.hxlstandard.org/data/validate.html?filter_count=7&url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1ytPD-f4a8CbNKTfMS3EqZOpBo9LWCk_NDKxJCgmpXA8%2Fedit%23gid%3D1101521524&schema_content=[{%22%23valid_tag%22%3A%22%23xxx%22%2C%20%22%23valid_required%22%3A%22true%22}]

**Comment by davidmegginson** [comment]
Usage: add _schema\_content_ as a GET or POST parameter, with a URL-encoded version of the schema. If using POST, the main content needs to be application/x-www-form-urlencoded to allow for additional POST params in the future.

The _schema\_url_ (GET only) and _schema\_content_ (GET or POST) params are both allowed. You can use _schema\_url_ for the general background schema, and _schema\_content_ for local customisations.

**Comment by davidmegginson** [comment]
@danmihaila - please verify and close.
