### ISSUE TITLE
Itos problem

### ISSUE THREAD

**Issue by danmihaila** [HXLStandard/hxl-proxy#213]
Found there are some issues with ITOS service. 
For BDI country - http://gistmaps.itos.uga.edu/arcgis/rest/services/COD_External there are 2 links and if you go to any it looks there are Adm0, Adm1 and Adm2 information. 
The hxl proxy is not getting information for Adm2 - https://beta.proxy.hxlstandard.org/pcodes/bdi-adm2.csv .It says the p-codes doesn't exist . We checked this url http://gistmaps.itos.uga.edu/arcgis/rest/services/COD_External/BDI_pcode/MapServer/2/query?where=1%3D1&outFields=*&returnGeometry=false&f=pjson and looks that it is working.
We need to be sure if the data is wrong with ITOS and do something about it. pinging @cjhendrix

**Comment by davidmegginson** [comment]
Fixed in #214
