### ISSUE TITLE
If validation fails it should return error in json format

### ISSUE THREAD

**Issue by danmihaila** [HXLStandard/hxl-proxy#218]
When validation fails due to a server error (or something went wrong :) )
https://beta.proxy.hxlstandard.org/data/validate.json?&url=https%3A%2F%2Ffeature-data.humdata.org%2Fdataset%2F9c7035b9-bfae-4da8-8446-a92d2fcd3b50%2Fresource%2Fd83dc255-55ab-4ea2-a222-bddc591ff7ad%2Fdownload%2Fhno-nigeria-2018.xls&schema_url=https%3A%2F%2Fraw.githubusercontent.com%2FOCHA-DAP%2Ftools-datacheck-validation%2Fprod%2Fbasic-validation-schema.json it should return a json error according to https://github.com/HXLStandard/hxl-proxy/issues/170#issuecomment-383235404

You can see data at https://beta.proxy.hxlstandard.org/data.json?&url=https%3A%2F%2Ffeature-data.humdata.org%2Fdataset%2F9c7035b9-bfae-4da8-8446-a92d2fcd3b50%2Fresource%2Fd83dc255-55ab-4ea2-a222-bddc591ff7ad%2Fdownload%2Fhno-nigeria-2018.xls&schema_url=https%3A%2F%2Fraw.githubusercontent.com%2FOCHA-DAP%2Ftools-datacheck-validation%2Fprod%2Fbasic-validation-schema.json

Note. header contains some merged cells…

**Comment by davidmegginson** [comment]
The actual bug fix will take place in HXLStandard/libhxl-python#151

**Comment by davidmegginson** [comment]
Fixed in hxl_proxy.controllers and noted in CHANGELOG

Verification link (trying to validate a non-existant file): https://beta.proxy.hxlstandard.org/data/validate.json?url=http%3A%2F%2Fexample.org%2Fnon-existant.csv

**Comment by davidmegginson** [comment]
@danmihaila - please confirm and close if OK

**Comment by davidmegginson** [comment]
Assuming fixed (since data check is showing the error message)
