### ISSUE TITLE
Allow users to POST a data source (validation only)

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/hxl-proxy#223]
Support a transactional workflow for validation only, where a user can upload _content_ via POST.

**Comment by davidmegginson** [comment]
Deployed to beta, using updated test branch of libhxl

**Comment by davidmegginson** [comment]
Lightly tested.

Documented at https://github.com/HXLStandard/hxl-proxy/wiki/Validation-service

Ready for dev team testing by @alexandru-m-g

**Comment by davidmegginson** [comment]
*Update:* CORS header needed

**Comment by davidmegginson** [comment]
_Update:_ optionally include the original parsed content in the result. Consider using a generator to conserve memory.

**Comment by alexandru-m-g** [comment]
@davidmegginson tested CORS and _include_dataset_ on beta proxy and it works great. 
Thanks

**Comment by davidmegginson** [comment]
Great! Closing.

**Comment by davidmegginson** [comment]
Roll back this change. Supported instead with a new endpoint via #223

**Comment by davidmegginson** [comment]
TODO: roll back old POST code at /data/validation

**Comment by alexandru-m-g** [comment]
@danmihaila also confirmed so it's ok to go ahead with this.
