### ISSUE TITLE
Add GeoJSON data download

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/hxl-proxy#24]
All rows with lat/lon or bounds turned into features.

Other columns become properties of each feature.

**Comment by SimonbJohnson** [comment]
Topojson would be a nice feature to have if possible!

**Comment by mikelmaron** [comment]
@davidmegginson I was just about to open a ticket with this request. It would be very useful for my case of processing the output of Kobo into GeoJSON, for further editing into OSM. I'm sure there are other cases as well. 

What was the reasoning to reject this issue?
