### ISSUE TITLE
Add UI support for concat() aggregator in count filter

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/hxl-proxy#248]
Implement UI support for concatenated values during aggregation.

See HXLStandard/libhxl-python#197

Attn @SimonbJohnson

**Comment by davidmegginson** [comment]
Added a "Concatenate" option to the Count filter for basic support.

Deployed to beta and documented in wiki. Test link: https://beta.proxy.hxlstandard.org/data/edit?filter01=count&count-tags01=%23org&count-type01-01=concat&count-pattern01-01=%23sector&count-header01-01=Count&count-column01-01=%23meta%2Bcount&url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1ytPD-f4a8CbNKTfMS3EqZOpBo9LWCk_NDKxJCgmpXA8%2Fedit%23gid%3D1101521524

**Comment by SimonbJohnson** [comment]
Working perfectly

https://beta.proxy.hxlstandard.org/data/b882f4

**Comment by davidmegginson** [comment]
Excellent! I'm planning to add similar support to the deduplication filter.
