### ISSUE TITLE
Prepare and deploy 1.13.1 bugfix release

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/hxl-proxy#256]
- [x] complete new libhxl release
- [x] wait until the new release is visible on PyPi
- [x] update version in setup.py and hxl_proxy/\_\_init\_\_.py
- [x] update libhxl version in requirements.txt and setup.py
- [x] check CHANGELOG
- [x] test in clean virtualenv
- [x] merge to test and push
- [x] test on beta (~/scripts/test-beta.sh)
- [x] merge to master and push
- [x] wait for and verify the build on docker hub succeeds: https://hub.docker.com/r/unocha/hxl-proxy/builds/
- [x] add git tag
- [x] create GitHub release
- [x] create PyPi release
- [x] deployed to staging (@teodorescuserban)
- [x] tested successfully in staging
- [x] deployed to prod (@teodorescuserban)
- [x] tested successfully in prod

**Comment by davidmegginson** [comment]
@teodorescuserban when convenient, you could deploy this new release to staging? Thanks!

**Comment by teodorescuserban** [comment]
sorry, missed it, deployed now.

**Comment by davidmegginson** [comment]
Tested successfully in staging and prod.
