### ISSUE TITLE
Deploy HXL Proxy 1.15 release

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/hxl-proxy#258]
- [x] complete new libhxl release
- [x] wait until the new release is visible on PyPi
- [x] update version in setup.py and hxl_proxy/\_\_init\_\_.py
- [x] update libhxl version in requirements.txt and setup.py
- [x] check CHANGELOG
- [x] test in clean virtualenv
- [x] merge to test and push
- [x] test on beta (~/scripts/test-beta.sh)
- [x] merge to master and push
- [x] wait for and verify the build on docker hub succeeds: https://hub.docker.com/r/unocha/hxl-proxy/builds/
- [x] add git tag
- [x] create GitHub release
- [x] create PyPi release
- [x] deployed to staging (@teodorescuserban)
- [x] tested successfully in staging
- [ ] deployed to prod (@teodorescuserban)
- [ ] tested successfully in prod

**Comment by davidmegginson** [comment]
GitHub: https://github.com/HXLStandard/hxl-proxy/releases/tag/1.15

**Comment by davidmegginson** [comment]
PyPi: https://pypi.org/project/hxl-proxy/1.15/

**Comment by davidmegginson** [comment]
@teodorescuserban - can you please put the new release on staging when you have a chance? (Monday is fine). Thanks!

**Comment by teodorescuserban** [comment]
@davidmegginson, deployed to staging.

**Comment by davidmegginson** [comment]
All tests passed in staging. Please deploy to prod on Monday (and let's hope no one notices it's April Fool's Day).

**Comment by davidmegginson** [comment]
Delay deployment to 1.15.1
