### ISSUE TITLE
Deploy interim 1.14.1 release to prod

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/hxl-proxy#262]
Requested by @danmihaila to bring #260 fix into production. No libhxl-python update required.

- [x] update version in setup.py and hxl_proxy/\_\_init\_\_.py
- [x] check CHANGELOG
- [x] test in clean virtualenv
- [x] merge to test and push
- [x] test on beta (~/scripts/test-beta.sh)
- [x] merge to master and push
- [x] wait for and verify the build on docker hub succeeds: https://hub.docker.com/r/unocha/hxl-proxy/builds/
- [x] add git tag
- [x] create GitHub release
- [x] create PyPi release
- [x] deployed to staging (@teodorescuserban)
- [x] tested successfully in staging
- [x] deployed to prod (@teodorescuserban)
- [x] tested successfully in prod

**Comment by davidmegginson** [comment]
GitHub release: https://github.com/HXLStandard/hxl-proxy/releases/tag/1.14.1

**Comment by davidmegginson** [comment]
PyPi release: https://pypi.org/project/hxl-proxy/1.14.1/

**Comment by davidmegginson** [comment]
@teodorescuserban - could you please deploy to staging? Thanks.

**Comment by teodorescuserban** [comment]
deployed @davidmegginson, excuse the delay

**Comment by davidmegginson** [comment]
Thanks, @teodorescuserban . All tests pass. Please go ahead and deploy to production.

**Comment by teodorescuserban** [comment]
Prod deployed, @davidmegginson

**Comment by davidmegginson** [comment]
Thank you, @teodorescuserban ! Tested successfully. Closing.
