### ISSUE TITLE
filter to replace tags and titles

### ISSUE THREAD

**Issue by SimonbJohnson** [HXLStandard/hxl-proxy#271]
Sometimes a tag or header needs replacing on a column to get the desired output

**Comment by davidmegginson** [comment]
If I understand the requirement correctly, the [Rename column filter](https://github.com/HXLStandard/hxl-proxy/wiki/Rename-column-filter) can do either or both.

**Comment by SimonbJohnson** [comment]
Not sure how I missed that!  Does exactly what I need, closing
