### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by AndrewM014** [HXLStandard/hxl-proxy#283]
https://proxy.hxlstandard.org/data/d26ba2/validate 

Keeps crashing when i validate

**Comment by davidmegginson** [comment]
Thanks for the report—I will investigate today.

**Comment by davidmegginson** [comment]
The problem is that your name has accidentally been pasted into the schema URL field. You can either leave the field blank to use the default schema, or paste in a URL pointing to a custom HXL schema:

https://proxy.hxlstandard.org/data/d26ba2/edit
