### ISSUE TITLE
IF row formula

### ISSUE THREAD

**Issue by mikelmaron** [HXLStandard/hxl-proxy#284]
Request to create a `IF` row formula. If the first argument is not null, then apply the value in the second argument to the cell in the row.

For example, I have a recipe step that applies the Add Column Filter to create a new column with a full url to an image. Would like to do something like this, to only create the url if there is a value set.

`{{if(#image, "http://kc.humanitarianresponse.info/attachment/orginal?media_file=mapkibera/attachments/"+#image)}}`

IF may not be the right label for this formula, as it's basically IF NOT NULL, and not a general IF.

**Comment by mikelmaron** [comment]
Maybe https://github.com/HXLStandard/hxl-proxy/wiki/Replace-data-filter will do what I need here. Actually fairly sure it will.

**Comment by davidmegginson** [comment]
If it doesn't, let me know. I have been considering adding an if() function when I'm able to free up more time to work on the Proxy. It's a bit trickier than other functions, because I'd have to add a language for conditions as well.

**Comment by mikelmaron** [comment]
applying regex works great for my use cases
