### ISSUE TITLE
freetext labels for filters in a recipe

### ISSUE THREAD

**Issue by mikelmaron** [HXLStandard/hxl-proxy#286]
For a recipe with many filters, it becomes hard to understand what each step is without clicking into the filter. Allow in the filter dialog to assign an option label, which would be displayed in addition to the filter name in the Recipe listing

**Comment by davidmegginson** [comment]
@mikelmaron - this is implemented now in the beta version of the HXL Proxy, and should roll out to production in the next week or two. Here's a sample link:

https://beta.proxy.hxlstandard.org/data/edit?dest=data_edit&filter01=clean&filter-label01=Simplify+the+IDs&clean-num-tags01=%23meta%2Bid&filter02=sort&filter-label02=Sort+by+country&sort-tags02=%23country&filter03=add&filter-label03=Add+fixed+donor+name+to+all+rows.&add-tag03=%23org%2Bfunding&add-value03=Foolandia&add-header03=Proveedor+de+fondos&url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1ytPD-f4a8CbNKTfMS3EqZOpBo9LWCk_NDKxJCgmpXA8%2Fedit%23gid%3D1101521524

**Comment by davidmegginson** [comment]
![image](https://user-images.githubusercontent.com/2810060/79801483-39d0b400-832c-11ea-8a51-2632ebc99f33.png)

**Comment by mikelmaron** [comment]
👏
