### ISSUE TITLE
Issues with redis caching backend

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/hxl-proxy#307]
Reported by @teodorescuserban in https://humanitarian.atlassian.net/browse/HDX-6840

> There seems to be two issues with redis cache support:
> * i cant make it use the hostname “redis” instead of “localhost” (see confing used below)
> * it looks like the requests made to amazon s3 content is also cached; since the amazon url expires and returns 401 afterwards, this is a problem only if hxlproxy will not try again to get the updated amazon url from ckan.

> The hostname setting part is a blocker for redis.

**Comment by davidmegginson** [comment]
Cannot reproduce. See comment on the Altassian issue:
> 1. On my laptop, try viewing a page with caching – OK.
> 2. Change CACHE_REDIS_HOST from “127.0.0.1” to “redis” and restart the web server – HTTP 500 error trying to view the page.
> 3. Assign the host “redis” to 127.0.0.1 in /etc/hosts and restart the web server – page displays correctly.
> Unfortunately, there’s nothing else I can do at my end to fix this. I looks like requests-cache is picking up the redis hostname correctly, given what I observed above. Pip says that I have version 0.5.0 of the Python requests_cache package. Serban Teodorescu – can you confirm what version got picked up where you were experimenting? We could try hard-coding requests_cache=0.5.0 in requirements.txt and see if it helps.
> Otherwise, can we confirm that the hostname “redis” resolves and is accessible from the VM where you’re working? What happens when you use an IP address instead of a hostname?

**Comment by teodorescuserban** [comment]
@David Megginson <dpm@megginson.com> Please post in the ticket your whole
config.
Thank you.

**Comment by teodorescuserban** [comment]
@davidmegginson i got requests-cache==0.5.2

**Comment by teodorescuserban** [comment]
I am on the dev branch, at 
```commit 822f8186b935083796e97989639e02b1ee400308 (HEAD -> dev, origin/test, origin/dev)
Author: David Megginson <david.megginson@gmail.com>
Date:   Sat Mar 7 14:17:16 2020 -0500

    Add header as optional second selector for rename column filter. Fixes #305

commit 79a0e6f5229d41cf19ad98d010895dc4af5103d9```


My [docker-compose] setup is:
```
services:
  com:
    environment:
      REDIS_HOSTS: local:redis:6379,local:proxy:6379
    image: unocha/redis-commander:0.6.4
    ports:
    - 0.0.0.0:3000:3000/tcp
  proxy:
    entrypoint: sleep 3600
    environment:
      HXL_PROXY_CONFIG: /srv/www/config.py
    image: unocha/alpine-base-s6-python3:3.8
    ports:
    - 0.0.0.0:5000:5000/tcp
    - 0.0.0.0:6379:6379/tcp
    volumes:
    - ./:/srv/www
  redis:
    image: unocha/alpine-redis:3.2.8
version: '2.2'```

**Comment by davidmegginson** [comment]
@teodorescuserban After the AWS migration is finished, it would be great if I could beg an hour of your time to work on this bug with me. I think the redis caching will be especially valuable on AWS.

**Comment by teodorescuserban** [comment]
Roger @davidmegginson

**Comment by davidmegginson** [comment]
This appears to be stale/resolved

**Comment by teodorescuserban** [comment]
yep, unfortunately redis cache is not the best for our use case.
