### ISSUE TITLE
Prepare and deploy 1.19 release

### ISSUE THREAD

**Issue by danmihaila** [HXLStandard/hxl-proxy#312]
- [x] libhxl-python release 4.19 on PyPi (@davidmegginson)
- [x] confirm all other issues closed or moved to a different milestone
- [x] confirm all hxl-proxy unit tests pass
- [x] update version to "1.19" in both setup.py and hxl_proxy/\_\_init\_\_.py
- [x] update libhxl requirement in requirements.txt and setup.py to v.4.19
- [x] confirm CHANGELOG up to date
- [x] check in git dev branch
- [x] test in clean virtualenv
- [x] test Docker build locally: ``$ sudo docker build --no-cache -t unocha/hxl-proxy:local .``
- [x] merge to git master branch and push
- [x] add git tag "1.19"
- [x] create GitHub release 1.19
- [x] create PyPi release: ``$ python3 setup.py sdist upload``
- [x] wait for and verify the 1.19 build on docker hub succeeds: https://hub.docker.com/r/unocha/hxl-proxy/builds/
- [x] deploy to staging
- [x] test in staging using test links
- [x] deploy to prod
- [x] test in prod using test links

**Comment by davidmegginson** [comment]
Deployed and tested successfully.
