### ISSUE TITLE
JSONPath or similar definition for input JSON

### ISSUE THREAD

**Issue by mcarans** [HXLStandard/hxl-proxy#314]
Minimally, it would be great to use JSONPath to specify the root node for the proxy to find the data.

eg.
```
{fields: {...}, data: {[1,2,3,4],[5,6,7,8]}}
```
For the above, if the data has no headers (because they are listed in fields in this case), it would be good to be able to handle that case by allowing the user to just specify the HXL tags by column (I have raised this as a separate issue https://github.com/HXLStandard/hxl-proxy/issues/315).

It would be even better to be able to use JSONPath or similar to be able to say look in the "attributes" key of each dictionary for the data in the following example:

```
{"objectIdFieldName":"OBJECTID","uniqueIdField":{"name":"OBJECTID","isSystemMaintained":true},"geometryType":"esriGeometryPoint","fields":[{"name":"OBJECTID","type":"esriFieldTypeOID","alias":"OBJECTID","sqlType":"sqlTypeOther","domain":null,"defaultValue":null},...{"OBJECTID":1,"ISO_2_CODE":"AF","ISO_3_CODE":"AFG","ADM0_NAME":"Afghanistan","date_epicrv":1582502400000,"NewCase":1,"CumCase":1,"NewDeath":0,"CumDeath":0,...},"geometry":{"x":66.026529770000081,"y":33.838901157000066}},{"attributes":{"OBJECTID":2,"ISO_2_CODE":"AF","ISO_3_CODE":"AFG","ADM0_NAME":"Afghanistan","date_epicrv":1582588800000,"NewCase":0,"CumCase":1,"NewDeath":0,"CumDeath":0...}
``

**Comment by davidmegginson** [comment]
Presumably already supported on the libhxl side: https://github.com/HXLStandard/libhxl-python/issues/166

(need to confirm)

**Comment by davidmegginson** [comment]
No, it wasn't support. Reopened https://github.com/HXLStandard/libhxl-python/issues/99

**Comment by davidmegginson** [comment]
Implemented and deployed to beta Proxy. Confirmation links (same input file with different JSONpath selectors):

* $.sel1 - https://beta.proxy.hxlstandard.org/data/edit?dest=data_view&url=https%3A%2F%2Fraw.githubusercontent.com%2FHXLStandard%2Flibhxl-python%2Fmaster%2Ftests%2Ffiles%2Ftest_io%2Finput-valid-json-selector.json&selector=%24.sel1&dest=data_view
* $.sel2 - https://beta.proxy.hxlstandard.org/data/edit?dest=data_view&url=https%3A%2F%2Fraw.githubusercontent.com%2FHXLStandard%2Flibhxl-python%2Fmaster%2Ftests%2Ffiles%2Ftest_io%2Finput-valid-json-selector.json&selector=%24.sel2&dest=data_view

**Comment by mcarans** [comment]
1. Worked well for https://dashboards-dev.sprinklr.com/data/9043/global-covid19-who-gis.json - now all that is needed for that url is to be able to define HXL tags where there are no headers. (jsonpath = rows)

2. Didn't work for https://services.arcgis.com/5T5nSi527N4F7luB/arcgis/rest/services/COVID19_hist_cases_adm0_v5_view/FeatureServer/0/query?outFields=*&where=1%3D1&f=json - I tested jsonpath here: https://jsonpath.com/ and came up with jsonpath=features[*].attributes. I tried in the HXL Proxy and got error: "<HXLException: Could not usable JSON data (need array of objects or array of arrays)>", but the evaluation of the jsonpath should have produced an array of objects.
