### ISSUE TITLE
Tagger function fails if headers are the same

### ISSUE THREAD

**Issue by SimonbJohnson** [HXLStandard/hxl-proxy#331]
This [link](https://proxy.hxlstandard.org/data/edit?tagger-match-all=on&tagger-01-header=%28a-z%29&tagger-01-tag=%23country&tagger-02-header=%28a-z%29&tagger-02-tag=%23country%2Bcode%2Bv_iso3&tagger-03-header=%280-10%29&tagger-03-tag=%23indicator%2Bperson2person&tagger-04-header=%280-10%29&tagger-04-tag=%23indicator%2Bcovid19%2Bhazard%2Bexposure&tagger-05-header=%280-10%29&tagger-05-tag=%23indicator%2Bdevelopment%2Bdeprivation&tagger-06-header=%280-10%29&tagger-06-tag=%23indicator%2Binequality&tagger-07-header=%280-10%29&tagger-07-tag=%23indicator%2Baid%2Bdependency&tagger-08-header=%280-10%29&tagger-08-tag=%23indicator%2Bsocioeconomic%2Bvulnerability&tagger-09-header=%280-10%29&tagger-09-tag=%23indicator%2Buprooted%2Bpeople&tagger-10-header=%280-10%29&tagger-10-tag=%23indicator%2Bhealth%2Bconditions&tagger-11-header=%280-10%29&tagger-11-tag=%23indicator%2Bfood%2Bsecurity&tagger-12-header=%280-10%29&tagger-12-tag=%23indicator%2Bgbv&tagger-13-header=%280-10%29&tagger-13-tag=%23indicator%2Bvulnerable%2Bgroups&tagger-14-header=%280-10%29&tagger-14-tag=%23indicator%2Bvulnerability%2Bhazard%2Bindependent&tagger-15-header=%280-10%29&tagger-15-tag=%23indicator%2Bmovements&tagger-16-header=%280-10%29&tagger-16-tag=%23indicator%2Bbehaviour&tagger-17-header=%280-10%29&tagger-17-tag=%23indicator%2Bdemographic%2Bcomorbidity&tagger-18-header=%280-10%29&tagger-18-tag=%23indicator%2Bcovid19%2Bvulnerability&tagger-19-header=%280-10%29&tagger-19-tag=%23indicator%2Bvulnerability&tagger-20-header=%280-10%29&tagger-20-tag=%23indicator%2Bdrr&tagger-21-header=%280-10%29&tagger-21-tag=%23indicator%2Bgovernance&tagger-22-header=%280-10%29&tagger-22-tag=%23indicator%2Binstitutional&tagger-23-header=%280-10%29&tagger-23-tag=%23indicator%2Baccess%2Bhealthcare&tagger-24-header=%280-10%29&tagger-24-tag=%23indicator%2Binfrastructure&tagger-25-header=%280-10%29&tagger-25-tag=%23indicator%2Black%2Bcoping%2Bcapacity%2Bhazard%2Bindependent&tagger-26-header=%280-10%29&tagger-26-tag=%23indicator&tagger-27-header=%280-10%29&tagger-27-tag=%23indicator&tagger-28-header=%280-10%29&tagger-28-tag=%23indicator&tagger-29-header=%280-10%29&tagger-29-tag=%23indicator&tagger-30-header=%280-10%29&tagger-30-tag=%23indicator&tagger-31-header=%280-10%29&tagger-31-tag=%23indicator&tagger-32-header=%280-10%29&tagger-32-tag=%23indicator&tagger-33-header=%28very+low-very+high%29&tagger-33-tag=%23indicator&tagger-34-header=%281-191%29&tagger-34-tag=%23indicator&tagger-35-header=%280-10%29&tagger-35-tag=%23indicator&tagger-36-header=%280-50%29&tagger-36-tag=%23indicator&tagger-37-header=%280-100%25%29&tagger-37-tag=%23indicator&url=https%3A%2F%2Fdata.humdata.org%2Fdataset%2Finform-covid-19-risk-index-version-0-1-2&sheet=2&header-row=3&dest=data_view) shows how if the headers are the same then it pulls through the incorrect tags.

Thanks to @Zibethin for finding

**Comment by davidmegginson** [comment]
Hi, @SimonbJohnson -- thanks for the report. I think the link didn't make it through.

**Comment by SimonbJohnson** [comment]
Opps, here it is
https://proxy.hxlstandard.org/data/edit?tagger-match-all=on&tagger-01-header=%28a-z%29&tagger-01-tag=%23country&tagger-02-header=%28a-z%29&tagger-02-tag=%23country%2Bcode%2Bv_iso3&tagger-03-header=%280-10%29&tagger-03-tag=%23indicator%2Bperson2person&tagger-04-header=%280-10%29&tagger-04-tag=%23indicator%2Bcovid19%2Bhazard%2Bexposure&tagger-05-header=%280-10%29&tagger-05-tag=%23indicator%2Bdevelopment%2Bdeprivation&tagger-06-header=%280-10%29&tagger-06-tag=%23indicator%2Binequality&tagger-07-header=%280-10%29&tagger-07-tag=%23indicator%2Baid%2Bdependency&tagger-08-header=%280-10%29&tagger-08-tag=%23indicator%2Bsocioeconomic%2Bvulnerability&tagger-09-header=%280-10%29&tagger-09-tag=%23indicator%2Buprooted%2Bpeople&tagger-10-header=%280-10%29&tagger-10-tag=%23indicator%2Bhealth%2Bconditions&tagger-11-header=%280-10%29&tagger-11-tag=%23indicator%2Bfood%2Bsecurity&tagger-12-header=%280-10%29&tagger-12-tag=%23indicator%2Bgbv&tagger-13-header=%280-10%29&tagger-13-tag=%23indicator%2Bvulnerable%2Bgroups&tagger-14-header=%280-10%29&tagger-14-tag=%23indicator%2Bvulnerability%2Bhazard%2Bindependent&tagger-15-header=%280-10%29&tagger-15-tag=%23indicator%2Bmovements&tagger-16-header=%280-10%29&tagger-16-tag=%23indicator%2Bbehaviour&tagger-17-header=%280-10%29&tagger-17-tag=%23indicator%2Bdemographic%2Bcomorbidity&tagger-18-header=%280-10%29&tagger-18-tag=%23indicator%2Bcovid19%2Bvulnerability&tagger-19-header=%280-10%29&tagger-19-tag=%23indicator%2Bvulnerability&tagger-20-header=%280-10%29&tagger-20-tag=%23indicator%2Bdrr&tagger-21-header=%280-10%29&tagger-21-tag=%23indicator%2Bgovernance&tagger-22-header=%280-10%29&tagger-22-tag=%23indicator%2Binstitutional&tagger-23-header=%280-10%29&tagger-23-tag=%23indicator%2Baccess%2Bhealthcare&tagger-24-header=%280-10%29&tagger-24-tag=%23indicator%2Binfrastructure&tagger-25-header=%280-10%29&tagger-25-tag=%23indicator%2Black%2Bcoping%2Bcapacity%2Bhazard%2Bindependent&tagger-26-header=%280-10%29&tagger-26-tag=%23indicator&tagger-27-header=%280-10%29&tagger-27-tag=%23indicator&tagger-28-header=%280-10%29&tagger-28-tag=%23indicator&tagger-29-header=%280-10%29&tagger-29-tag=%23indicator&tagger-30-header=%280-10%29&tagger-30-tag=%23indicator&tagger-31-header=%280-10%29&tagger-31-tag=%23indicator&tagger-32-header=%280-10%29&tagger-32-tag=%23indicator&tagger-33-header=%28very+low-very+high%29&tagger-33-tag=%23indicator&tagger-34-header=%281-191%29&tagger-34-tag=%23indicator&tagger-35-header=%280-10%29&tagger-35-tag=%23indicator&tagger-36-header=%280-50%29&tagger-36-tag=%23indicator&tagger-37-header=%280-100%25%29&tagger-37-tag=%23indicator&url=https%3A%2F%2Fdata.humdata.org%2Fdataset%2Finform-covid-19-risk-index-version-0-1-2&sheet=2&header-row=3&dest=data_view

**Comment by davidmegginson** [comment]
Related to https://github.com/HXLStandard/libhxl-python/issues/241 (it needs to be resolved there first)

**Comment by davidmegginson** [comment]
Also mostly covered by #315

The challenge is that the tagger operates (for now) purely by string matching, though that's not obvious from the HXL Proxy UI (which prepopulates the form positionally based on the input data).

**Comment by davidmegginson** [comment]
I won't be able to include positional support for this release, but there's a simple workaround: use the actual header row for the tagger mapping, then remove the comment row beneath it ("(0-10)", etc) using a row filter.

https://proxy.hxlstandard.org/data/edit?tagger-match-all=on&tagger-01-header=%28a-z%29&tagger-01-tag=%23country&tagger-02-header=%28a-z%29&tagger-02-tag=%23country%2Bcode%2Bv_iso3&tagger-03-header=%280-10%29&tagger-03-tag=%23indicator%2Bperson2person&tagger-04-header=%280-10%29&tagger-04-tag=%23indicator%2Bcovid19%2Bhazard%2Bexposure&tagger-05-header=%280-10%29&tagger-05-tag=%23indicator%2Bdevelopment%2Bdeprivation&tagger-06-header=%280-10%29&tagger-06-tag=%23indicator%2Binequality&tagger-07-header=%280-10%29&tagger-07-tag=%23indicator%2Baid%2Bdependency&tagger-08-header=%280-10%29&tagger-08-tag=%23indicator%2Bsocioeconomic%2Bvulnerability&tagger-09-header=%280-10%29&tagger-09-tag=%23indicator%2Buprooted%2Bpeople&tagger-10-header=%280-10%29&tagger-10-tag=%23indicator%2Bhealth%2Bconditions&tagger-11-header=%280-10%29&tagger-11-tag=%23indicator%2Bfood%2Bsecurity&tagger-12-header=%280-10%29&tagger-12-tag=%23indicator%2Bgbv&tagger-13-header=%280-10%29&tagger-13-tag=%23indicator%2Bvulnerable%2Bgroups&tagger-14-header=%280-10%29&tagger-14-tag=%23indicator%2Bvulnerability%2Bhazard%2Bindependent&tagger-15-header=%280-10%29&tagger-15-tag=%23indicator%2Bmovements&tagger-16-header=%280-10%29&tagger-16-tag=%23indicator%2Bbehaviour&tagger-17-header=%280-10%29&tagger-17-tag=%23indicator%2Bdemographic%2Bcomorbidity&tagger-18-header=%280-10%29&tagger-18-tag=%23indicator%2Bcovid19%2Bvulnerability&tagger-19-header=%280-10%29&tagger-19-tag=%23indicator%2Bvulnerability&tagger-20-header=%280-10%29&tagger-20-tag=%23indicator%2Bdrr&tagger-21-header=%280-10%29&tagger-21-tag=%23indicator%2Bgovernance&tagger-22-header=%280-10%29&tagger-22-tag=%23indicator%2Binstitutional&tagger-23-header=%280-10%29&tagger-23-tag=%23indicator%2Baccess%2Bhealthcare&tagger-24-header=%280-10%29&tagger-24-tag=%23indicator%2Binfrastructure&tagger-25-header=%280-10%29&tagger-25-tag=%23indicator%2Black%2Bcoping%2Bcapacity%2Bhazard%2Bindependent&tagger-26-header=%280-10%29&tagger-26-tag=%23indicator&tagger-27-header=%280-10%29&tagger-27-tag=%23indicator&tagger-28-header=%280-10%29&tagger-28-tag=%23indicator&tagger-29-header=%280-10%29&tagger-29-tag=%23indicator&tagger-30-header=%280-10%29&tagger-30-tag=%23indicator&tagger-31-header=%280-10%29&tagger-31-tag=%23indicator&tagger-32-header=%280-10%29&tagger-32-tag=%23indicator&tagger-33-header=%28very+low-very+high%29&tagger-33-tag=%23indicator&tagger-34-header=%281-191%29&tagger-34-tag=%23indicator&tagger-35-header=%280-10%29&tagger-35-tag=%23indicator&tagger-36-header=%280-50%29&tagger-36-tag=%23indicator&tagger-37-header=%280-100%25%29&tagger-37-tag=%23indicator&url=https%3A%2F%2Fdata.humdata.org%2Fdataset%2Finform-covid-19-risk-index-version-0-1-2&sheet=2&header-row=3&dest=data_view

**Comment by davidmegginson** [comment]
Moved to Jira
