### ISSUE TITLE
When tagging non HXL data headers have to be adjacent to the data, but this may not be the case.

### ISSUE THREAD

**Issue by SimonbJohnson** [HXLStandard/hxl-proxy#332]
In the HXL standard where the headers appears is well defined. When tagging a non HXLated dataset the headers might not be directly adjacent to the data, e.g. https://data.humdata.org/dataset/inform-covid-19-risk-index-version-0-1-2, but the HXL Proxy does not account for this.

A work around for this is to pick the header and then use filters to remove the extra header rows:
https://proxy.hxlstandard.org/data/edit?dest=data_edit&filter01=select&filter-label01=Remove+second+header+row&select-query01-01=%23country%2Bname+%3D+%28a-z%29&select-reverse01=on&tagger-match-all=on&tagger-01-header=country&tagger-01-tag=%23country%2Bname&tagger-02-header=iso3&tagger-02-tag=%23country%2Bcode&tagger-03-header=p2p&tagger-03-tag=%23indicator%2Bperson2person&tagger-04-header=covid-19+hazard+%26+exposure&tagger-04-tag=%23indicator%2Bcovid19%2Bhazard%2Bexposure&tagger-05-header=development+%26+deprivation&tagger-05-tag=%23indicator%2Bdevelopment%2Bdeprivation&tagger-06-header=inequality&tagger-06-tag=%23indicator%2Binequality&tagger-07-header=aid+dependency&tagger-07-tag=%23indicator%2Baid%2Bdependency&tagger-08-header=socio-economic+vulnerability&tagger-08-tag=%23indicator%2Bsocioeconomic%2Bvulnerability&tagger-09-header=uprooted+people&tagger-09-tag=%23indicator%2Buprooted%2Bpeople&tagger-10-header=health+conditions&tagger-10-tag=%23indicator%2Bhealth%2Bconditions&tagger-11-header=children+u5&tagger-11-tag=%23indicator&tagger-12-header=recent+shocks&tagger-12-tag=%23indicator%2Brecent_shocks&tagger-13-header=food+security&tagger-13-tag=%23indicator%2Bfood%2Bsecurity&tagger-14-header=gbv&tagger-14-tag=%23indicator%2Bgbv&tagger-15-header=vulnerable+groups&tagger-15-tag=%23indicator%2Bvulnerable%2Bgroups&tagger-16-header=vulnerability+%28hazard-independent%29&tagger-16-tag=%23indicator%2Bvulnerable%2Bhazards&tagger-17-header=movements&tagger-17-tag=%23indicator%2Bmovements&tagger-18-header=behaviour&tagger-18-tag=%23indicator&tagger-19-header=demographic+and+co-morbidity&tagger-19-tag=%23indicator&tagger-20-header=covid-19+vulnerability&tagger-20-tag=%23indicator%2Bcovid_19%2Bvulnerability&tagger-21-header=vulnerability&tagger-21-tag=%23indicator%2Bvulnerability&tagger-22-header=drr&tagger-22-tag=%23indicator%2Bdrr&tagger-23-header=governance&tagger-23-tag=%23indicator%2Bgovernance&tagger-24-header=institutional&tagger-24-tag=%23indicator%2Binstitutional&tagger-25-header=communication&tagger-25-tag=%23indicator%2Bcommunication&tagger-26-header=physical+infrastructure&tagger-26-tag=%23indicator&tagger-27-header=access+to+health+care&tagger-27-tag=%23indicator&tagger-28-header=infrastructure&tagger-28-tag=%23indicator&tagger-29-header=lack+of+coping+capacity+%28hazard-independent%29&tagger-29-tag=%23indicator&tagger-30-header=covid-19+lack+of+coping+capacity&tagger-30-tag=%23indicator&tagger-31-header=lack+of+coping+capacity&tagger-31-tag=%23indicator&tagger-32-header=inform+covid-19+risk&tagger-32-tag=%23indicator&tagger-33-header=covid-19+risk+class&tagger-33-tag=%23indicator&tagger-34-header=rank&tagger-34-tag=%23indicator&tagger-35-header=lack+of+reliability+%28*%29&tagger-35-tag=%23indicator&tagger-36-header=number+of+missing+indicators&tagger-36-tag=%23indicator&tagger-37-header=%25+of+missing+indicators&tagger-37-tag=%23indicator&header-row=2&url=https%3A%2F%2Fdata.humdata.org%2Fdataset%2Finform-covid-19-risk-index-version-0-1-2&sheet=2

**Comment by davidmegginson** [comment]
Moved to Jira
