### ISSUE TITLE
SSRF via the url parameter

### ISSUE THREAD

**Issue by Ug0Security** [HXLStandard/hxl-proxy#341]
Hi,

there's a SSRF via the url parameter

https://proxy.hxlstandard.org/data/tagger?url=http://169.254.169.254/latest/meta-data/hostname
https://proxy.hxlstandard.org/data/validate?url=http%3A%2F%2F169.254.169.254%2Flatest%2Fmeta-data%2Fhostname

thx god it refuse to process json.. 

so the aws keys seems safe .. but still ^^

**Comment by Ug0Security** [comment]
ok i just found a way to make it extract aws key..  /!\

**Comment by teodorescuserban** [comment]
Many thanks for reporting this, @Ug0Security. We believe we have patched the issue temporarily and will discuss how to implement a more permanent solution.

Is it ok to contact you by email to ask you to provide more details on how the aws key has been obtained?

**Comment by Ug0Security** [comment]
yeah sure c.vallicari@gmail.com

**Comment by Ug0Security** [comment]
Patched in less than 17 hours, impressive, nice job :)

**Comment by davidmegginson** [comment]
Thank you for reporting this, and thank you Serban for addressing the issue
so quickly.  It's great that I'll be starting work Monday morning with a
solution instead of a problem. :)

D
