### ISSUE TITLE
Deploy bugfix for caching 1.24.3

### ISSUE THREAD

**Issue by danmihaila** [HXLStandard/hxl-proxy#375]
- [x] confirm all hxl-proxy unit tests pass
- [x] update version to "1.24.3" in both setup.py and hxl_proxy/\_\_init\_\_.py
- [x] confirm CHANGELOG up to date
- [x] commit changes
- [x] test in clean virtualenv
- [x] merge to git test branch and push
- [x] merge to git master branch and push
- [x] add git tag "1.24.3"
- [x] create GitHub release 1.24.3
- [x] create PyPi release: ``pip install twine && rm -rf dist/* && python setup.py sdist && twine upload dist/*``
- [x] wait for and verify the 1.24.3 build on docker hub succeeds: https://hub.docker.com/r/unocha/hxl-proxy/builds/
- [x] deploy to staging
- [x] test in staging using test links: ``$ cat tests/browser-tests/staging-urls.txt | xargs -d '\n' firefox`` (or for macos users: ``for url in $(cat tests/browser-tests/staging-urls.txt); do open $url; done`` )
- [x] deploy to prod
- [x] test in prod using test links: ``$ cat tests/browser-tests/prod-urls.txt | xargs -d '\n' firefox`` (or for macos users: ``for url in $(cat tests/browser-tests/prod-urls.txt); do open $url; done`` )

**Comment by teodorescuserban** [comment]
@danmihaila the missing item should be checking here: https://gallery.ecr.aws/unocha/hxl-proxy (and you can check it and close this issue).
