### ISSUE TITLE
Fix log format

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/hxl-proxy#392]
Log format should include a timestamp and severity.

**Comment by davidmegginson** [comment]
See https://stackoverflow.com/questions/55357513/how-to-change-flask-logging-debug-screen-output-format

**Comment by davidmegginson** [comment]
Sample of the new logging output format:
```
[2022-07-12 10:12:47,788] ERROR in hxl_proxy: *** Test message ***
```

**Comment by teodorescuserban** [comment]
If you think we would need to filter out for something inside the message itself (inside `*** Test message ***`), it would be better to make it parsable to put that bit in its own "field".

E.g:
```
[2022-07-12 10:12:47,788] ERROR in hxl_proxy: important_bit1 important bit_2 *** The rest of the test message ***
```

**Comment by teodorescuserban** [comment]
I was thinking on trying to wrap the error messages from flask to make more sense in the end. I think the libs errors dont need to change just for this only reason.

**Comment by davidmegginson** [comment]
Tested and deployed.
