### ISSUE TITLE
Support a local blocklist for domains

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/hxl-proxy#394]
Add a local blocklist for domains, with pattern matching.

**Comment by davidmegginson** [comment]
An example of a URL that should be blocked:

https://proxy.hxlstandard.org/data/tagger?url=http://dahanda.net/bbs/board.php?bo_table=free&wr_id=10250

**Comment by davidmegginson** [comment]
The report on the 2 July incident suggests the requests were coming from many different IPs, and @teodorescuserban was skeptical that we'd be able to come up with good regexes to block gambling sites, so I'm going to take this issue out of the current milestone.

**Comment by emmajane** [comment]
@davidmegginson External services can be viewed on NewRelic. Link added to the Slack channel.
<img width="242" alt="Screenshot 2022-08-09 at 14 28 02" src="https://user-images.githubusercontent.com/1299320/183659194-502bbc74-21e7-482d-84bd-f261450a036c.png">

**Comment by teodorescuserban** [comment]
This should now be closed, @davidmegginson, right?

**Comment by davidmegginson** [comment]
I have an approach in mind. I'm going to review your PR and see if it's closely aligned, and if so, then I can accept it.

**Comment by davidmegginson** [comment]
Thanks, @teodorescuserban.  I merged the PR, and it's a great start, but unfortunately, it misses a lot of cases. Most of the time, the HXL Proxy doesn't call the low-level hxl.input.make_input() directly, but calls the higher-level hxl.data() function. Not all of those should be wrapped, because sometimes the HXL Proxy gets data uploaded directly by the dev team (e.g. via a POST request). I'm going to work my way through.

**Comment by davidmegginson** [comment]
The wrappers are now util.hxl_data() and util.make_input(). They both use a common function to check if a URL is allowed, and raise an exception if not. The exception is a subclass of IOError, so that we can add more properties and provide a better user experience in the future (e.g. more-helpful contact info to request adding a domain).

**Comment by davidmegginson** [comment]
Implementation completed in ed7d8e14b5781996ffe315f13251ef32d86b3ae0

The wrappers are now hxl_proxy.util.hxl_data() and hxl_proxy.util.hxl_make_input()

**Comment by teodorescuserban** [comment]
> Implementation completed in [ed7d8e1](https://github.com/HXLStandard/hxl-proxy/commit/ed7d8e14b5781996ffe315f13251ef32d86b3ae0)
this looks good, but is about allowlist not blocklist right?
> 
> The wrappers are now hxl_proxy.util.hxl_data() and hxl_proxy.util.hxl_make_input()

**Comment by davidmegginson** [comment]
Thanks, @teodorescuserban . You're right that it is an allow list (I've updated the title). Did you have a chance to test? I'll try deploying to one of our pre-release VMs today and testing, but it's working locally (I tried listing and unlisting various domains in the config, and it behaved as expected).

**Comment by teodorescuserban** [comment]
> Thanks, @teodorescuserban . You're right that it is an allow list (I've updated the title). Did you have a chance to test? I'll try deploying to one of our pre-release VMs today and testing, but it's working locally (I tried listing and unlisting various domains in the config, and it behaved as expected).

Just for reference: work great! Well done, @davidmegginson !
