### ISSUE TITLE
Change log level to ERROR

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/hxl-proxy#395]
Change the log level on the web side to avoid cluttering the server logs.

**Comment by davidmegginson** [comment]
The logging level is now configurable, and defaults to "ERROR" if unspecified.

Please test at https://hxl.innovation.humdata.org/

@teodorescuserban @danmihaila

**Comment by teodorescuserban** [comment]
Amended the config to be able to use env vars. https://github.com/HXLStandard/hxl-proxy/pull/398

**Comment by teodorescuserban** [comment]
Looks good on dev, @davidmegginson
