### ISSUE TITLE
[OPS-8509] Friendlier exception handling

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/hxl-proxy#400]
Produce useful log messages for some of the more-common exceptions.

From @teodorescuserban :

It looks like there are a few exceptions that are not being catched:

401 Client Error: Unauthorized for url

404 Not Found

requests.exceptions.SSLError: HTTPSConnectionPool(host='enchantedtraveltx.com', port=443): Max retries exceeded with url: /__media__/js/netsoltrademark.php?d=sexshop-ideal.ru (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1129)')))

urllib3.util.ssl_match_hostname.CertificateError: hostname 'bolshakovo.ru' doesn't match either of '*.timeweb.ru', 'timeweb.ru'

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='bolshakovo.ru', port=443): Max retries exceeded with url: /index.php?action=profile;u=440193 (Caused by SSLError(CertificateError("hostname 'bolshakovo.ru' doesn't match either of '*.timeweb.ru', 'timeweb.ru'")))

urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f74c22818b0>: Failed to establish a new connection: [Errno -2] Name does not resolve and urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='http', port=443): Max retries exceeded with url: //www.gryna.com/bbs/board.php?bo_table=free (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f74c22818b0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))

`This one should be turned into ERROR rather than CRITICAL: CRITICAL in hxl.input: Security settings forbid accessing local files or non http(s)/ftp(s) URL schemes: sample.test

**Comment by davidmegginson** [comment]
For "This one should be turned into ERROR rather than CRITICAL: CRITICAL in hxl.input: Security settings forbid accessing local files or non http(s)/ftp(s) URL schemes: sample.test" I think CRITICAL does make sense, because it's an attempt to access a local file on the server, and may represent an attack (it doesn't in this case, but it could just as easily be "/etc/passwd").

**Comment by teodorescuserban** [comment]
> For "This one should be turned into ERROR rather than CRITICAL: CRITICAL in hxl.input: Security settings forbid accessing local files or non http(s)/ftp(s) URL schemes: sample.test" I think CRITICAL does make sense, because it's an attempt to access a local file on the server, and may represent an attack (it doesn't in this case, but it could just as easily be "/etc/passwd").

I would argue that `CRITICAL` should be reserved for what it does break hxl proxy. And because hxl proxy is ran in multiple threads (by multiple nginx unit processes) there's almost nothing `CRITICAL` beside not having access to the cache or database. We can sort out the attacks by the actual message logged rather than by the log level.

**Comment by teodorescuserban** [comment]
For the others, trying to catch the most common exceptions and passthrough / customize their messages is enough. I dont expect to get all of them :)

**Comment by teodorescuserban** [comment]
`hxl.input.make_input` exception is bubbling up, we just need to intercept it and _NOT_ show tracebacks for selected exceptions (403, 404, etc).

**Comment by davidmegginson** [comment]
> > For "This one should be turned into ERROR rather than CRITICAL: CRITICAL in hxl.input: Security settings forbid accessing local files or non http(s)/ftp(s) URL schemes: sample.test" I think CRITICAL does make sense, because it's an attempt to access a local file on the server, and may represent an attack (it doesn't in this case, but it could just as easily be "/etc/passwd").
> 
> I would argue that `CRITICAL` should be reserved for what it does break hxl proxy. And because hxl proxy is ran in multiple threads (by multiple nginx unit processes) there's almost nothing `CRITICAL` beside not having access to the cache or database. We can sort out the attacks by the actual message logged rather than by the log level.

Will address in https://github.com/HXLStandard/libhxl-python/issues/303

**Comment by davidmegginson** [comment]
@teodorescuserban Please confirm that non-existent datasets are no longer being logged as critical. You will need to use the HEAD of the test branch for both libhxl-python and hxl-proxy for it to work (i.e., not the version of libhxl on PyPi). You can test by trying to open this URL:

https://dev.proxy-hxlstandard-org.ahconu.org/data?url=https%3A%2F%2Fexample.org%2Ffoo.csv

It should log as CRITICAL before you do an update, and ERROR afterwards.

**Comment by davidmegginson** [comment]
> `hxl.input.make_input` exception is bubbling up, we just need to intercept it and _NOT_ show tracebacks for selected exceptions (403, 404, etc).

I need to figure out why this is happening. All of those should be caught when DEBUG==False, and an error page returned instead. Do you have a sample link, @teodorescuserban ?

**Comment by teodorescuserban** [comment]
> @teodorescuserban Please confirm that non-existent datasets are no longer being logged as critical. You will need to use the HEAD of the test branch for both libhxl-python and hxl-proxy for it to work (i.e., not the version of libhxl on PyPi). You can test by trying to open this URL:
> 
> https://dev.proxy-hxlstandard-org.ahconu.org/data?url=https%3A%2F%2Fexample.org%2Ffoo.csv
> 
> It should log as CRITICAL before you do an update, and ERROR afterwards.

Indeed, it is now logged as `ERROR` but the trace is also there, we need to get rid of that. :)

```
[2022-08-05 07:22:47,793] ERROR in hxl.input: Cannot open URL https://example.org/foo.csv (404 Client Error: Not Found for url: https://example.org/foo.csv)
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/hxl/input.py", line 534, in open_url_or_file
    response.raise_for_status()
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
 ```

**Comment by teodorescuserban** [comment]
> > `hxl.input.make_input` exception is bubbling up, we just need to intercept it and _NOT_ show tracebacks for selected exceptions (403, 404, etc).
> 
> I need to figure out why this is happening. All of those should be caught when DEBUG==False, and an error page returned instead. Do you have a sample link, @teodorescuserban ?

https://dev.proxy-hxlstandard-org.ahconu.org/data?url=https://dev.proxy-hxlstandard-org.ahconu.org/foobar

**Comment by davidmegginson** [comment]
Thank you! There were two places that used logger.exception() rather than logger.error(). Fixed in libhxl-python, and confirmed that tracebacks are not appearing when DEBUG==False

See https://github.com/HXLStandard/libhxl-python/issues/305

**Comment by teodorescuserban** [comment]
The SSL errors part I think has not been addressed. Should we reopen this ticket or make a new one, @davidmegginson @emmajane ?
