### ISSUE TITLE
Give less information for an HTML dataset

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/hxl-proxy#404]
Possibly return a 404 "No data found" instead of saying that it's HTML, so that the Proxy can't be used for pinging.

**Comment by davidmegginson** [comment]
Note that /data/tagger and /data/edit catch their own exceptions and show the error internally. That needs to be changed for the HTML markup exception.

**Comment by teodorescuserban** [comment]
@davidmegginson, I think the last commit fails the tests.

**Comment by davidmegginson** [comment]
They were failing because requirements.txt was using libhxl==4.26 instead of the dev branch HEAD. I changed the file, and _thought_ it passed after that, but might have misunderstood.

**Comment by teodorescuserban** [comment]
It is recommend to keep referring in the `requirements.txt` to the proper branch / tag of libhxl-python that it should use, and only change it to the new tag once everything is done and the libhxl-python has already been released; making this part of the new hxl-proxy tag creation process should be ideal.

**Comment by davidmegginson** [comment]
Thanks, @teodorescuserban — I've added that to step 5 here: https://github.com/HXLStandard/hxl-proxy/issues/401
