### ISSUE TITLE
Put a time limit on flask responses

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/hxl-proxy#412]
Put a limit on how long a flask response can run, if possible, or confirm that the browser will kill the process.

**Comment by davidmegginson** [comment]
Some background: https://stackoverflow.com/questions/18581174/max-execution-time-for-function-in-python-flask

**Comment by davidmegginson** [comment]
multiprocessing.Process: https://stackoverflow.com/questions/492519/timeout-on-a-function-call

**Comment by teodorescuserban** [comment]
[Nginx unit request limits](https://unit.nginx.org/configuration/#request-limits) can tell nginx unit (our wsgi-to-http server) how long before it needs to signal the flask to stop the current request.
If Flask respond the the graceful request of nginx-unit, then there's no need for anything else.

**Comment by davidmegginson** [comment]
That sounds great! Shall we set up a test and see if it works?

**Comment by davidmegginson** [comment]
I'm pushing this issue to the next milestone, since Nginx configuration does not affect the HXL Proxy code itself.

**Comment by teodorescuserban** [comment]
Unfortunately, nginx unit wont kill the process, but instead "alerts it". What this means is not obvious. When I tested, the python process happily kept processing the data until it finished, disregarding whatever waving nginx unit was doing in the background. See also here: https://unit.nginx.org/configuration/#configuration-proc-mgmt-lmts

This means, we will need to at least get hxl proxy to read the nginx unit hand signals and behave accordingly

**Comment by davidmegginson** [comment]
It looks like the problem is specifically with async workers, and is a subject of debate for gunicorn: https://github.com/benoitc/gunicorn/pull/1730#issuecomment-375658620

**Comment by davidmegginson** [comment]
I need to do more research, but if gunicorn doesn't handle the nginx signal or pass it on, then we'll either have to abandon async workers or investigate some solution inside flask (which is less elegant, having a timeout in two places, but perhaps necessary).

**Comment by teodorescuserban** [comment]
> I need to do more research, but if gunicorn doesn't handle the nginx signal or pass it on, then we'll either have to abandon async workers or investigate some solution inside flask (which is less elegant, having a timeout in two places, but perhaps necessary).

We don't have gunicorn. We replaced it with [nginx unit](https://unit.nginx.org/) some time ago.

**Comment by davidmegginson** [comment]
Info on catching signals in Flask here: https://flask.palletsprojects.com/en/2.2.x/signals/

**Comment by davidmegginson** [comment]
The only outstanding issue is that it returns a 500 instead of 408. I haven't figured out how to catch the signal inside the Flask processing, so it terminates at the top level.
