### ISSUE TITLE
strip headers not working on json download

### ISSUE THREAD

**Issue by SimonbJohnson** [HXLStandard/hxl-proxy#52]

**Comment by davidmegginson** [comment]
Fixed in https://github.com/HXLStandard/libhxl-python/issues/41

**Comment by davidmegginson** [comment]
Fixed.  Example: http://proxy.hxlstandard.org/data.json?filter_count=7&url=https%3A//docs.google.com/spreadsheets/d/1_TFjKh_rcZmYFjgEDhDXoya16piFZHMpmZgLzrqlS5Y/export%3Fformat%3Dcsv%26gid%3D2125848767%26single%3Dtrue&strip-headers=on&format=html&filter01=count&count-tags01=org&count-aggregate-tag01=&filter02=rename&rename-oldtag02=meta%2Bcount&rename-newtag02=output%2Bactivities&rename-header02=Activities&filter03=&filter04=&filter05=&filter06=&filter07=
