### ISSUE TITLE
force parameter not working for cache refresh

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/hxl-proxy#54]
Reported by @SimonbJohnson.

**Comment by davidmegginson** [comment]
I cannot reproduce this bug.  I tried working from a Google Sheet, both directly and using the "Publish to the Web" functionality (as CSV), and my changes were always immediately reflected in the JSON output using the &force=1 parameter.

@SimonbJohnson - are you still seeing this bug?

**Comment by SimonbJohnson** [comment]
@davidmegginson No, it seems to be working now.
