### ISSUE TITLE
Filtering very slow for 5,000+ row Google Sheet

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/hxl-proxy#55]
@SimonbJohnson reports 16+-second response times for this, with the force parameter:

http://beta.proxy.hxlstandard.org/data/edit?filter_count=7&url=https%3A//docs.google.com/spreadsheets/d/1Z4YWDKWnrSJPcyFEyHawRck0SrXg6R0hBriH7gBZuqA/pub%3Fgid%3D0%26single%3Dtrue%26output%3Dcsv&strip-headers=on&format=html&filter01=cut&cut-include-tags01=%23adm3%2Bcode%2C%23reached%2Bhouseholds%2C%23activity%2Bdescription&cut-exclude-tags01=&filter02=count&count-tags02=%23adm3%2Bcode%2C%23activity%2Bdescription&count-aggregate-tag02=%23reached%2Bhouseholds&filter03=&filter04=&filter05=&filter06=&filter07=

**Comment by SimonbJohnson** [comment]
Filters no longer seem to work.  This requests which cut columns and aggregates, not longer carries out the operations

http://proxy.hxlstandard.org/data.json?filter_count=7&url=https%3A//docs.google.com/spreadsheets/d/1Z4YWDKWnrSJPcyFEyHawRck0SrXg6R0hBriH7gBZuqA/pub%3Fgid%3D0%26single%3Dtrue%26output%3Dcsv&strip-headers=on&format=html&filter01=cut&cut-include-tags01=#adm3%2Bcode%2C%23reached%2Bhouseholds%2C%23activity%2Bdescription&cut-exclude-tags01=&filter02=count&count-tags02=%23adm3%2Bcode%2C%23activity%2Bdescription&count-aggregate-tag02=%23reached%2Bhouseholds&filter03=&filter04=&filter05=&filter06=&filter07=

**Comment by davidmegginson** [comment]
For some reason, it's not picking up the second filter: http://proxy.hxlstandard.org/data/edit?filter_count=7&url=https%3A//docs.google.com/spreadsheets/d/1Z4YWDKWnrSJPcyFEyHawRck0SrXg6R0hBriH7gBZuqA/pub%3Fgid%3D0%26single%3Dtrue%26output%3Dcsv&strip-headers=on&format=html&filter01=cut&cut-include-tags01=#adm3%2Bcode%2C%23reached%2Bhouseholds%2C%23activity%2Bdescription&cut-exclude-tags01=&filter02=count&count-tags02=%23adm3%2Bcode%2C%23activity%2Bdescription&count-aggregate-tag02=%23reached%2Bhouseholds&filter03=&filter04=&filter05=&filter06=&filter07=

**Comment by davidmegginson** [comment]
This works: http://proxy.hxlstandard.org/data/edit?filter_count=7&url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1Z4YWDKWnrSJPcyFEyHawRck0SrXg6R0hBriH7gBZuqA%2Fpub%3Fgid%3D0%26single%3Dtrue%26output%3Dcsv&strip-headers=on&format=html&filter01=cut&cut-include-tags01=&cut-exclude-tags01=&filter02=count&count-tags02=adm3%2Bcode%2Cactivity%2Bdescription&count-aggregate-tag02=&filter03=&filter04=&filter05=&filter06=&filter07=

JSON: http://proxy.hxlstandard.org/data.json?filter_count=7&url=https%3A//docs.google.com/spreadsheets/d/1Z4YWDKWnrSJPcyFEyHawRck0SrXg6R0hBriH7gBZuqA/pub%3Fgid%3D0%26single%3Dtrue%26output%3Dcsv&strip-headers=on&format=html&filter01=cut&cut-include-tags01=&cut-exclude-tags01=&filter02=count&count-tags02=adm3%2Bcode%2Cactivity%2Bdescription&count-aggregate-tag02=&filter03=&filter04=&filter05=&filter06=&filter07=

Could your original URL have become broken, somehow?  I notice one of the '#' characters isn't escaped.

**Comment by SimonbJohnson** [comment]
Yes, that seems have been the case.  The URL works for the encoded version.  Still a slow response

**Comment by davidmegginson** [comment]
It looks to be an I/O problem, possibly related to the Python _requests_ library.  Profiling shows one call per character when working with a remote (HTTP) file, running through several method calls.  Skipping the proxy and working directly with the libhxl command-line tools, I get these times for counting the orgs in the file:

HTTP: 21.671 seconds
Local file: 0.655 seconds

That makes it pretty clear that the slow-down isn't in the internal libhxl filtering logic.

**Comment by davidmegginson** [comment]
Made changes to libhxl that have sped things up considerably.  Rolled out to beta, but not prod yet.  With a force (skipping the cache), now refreshes in about 2.5 seconds:

http://beta.proxy.hxlstandard.org/data/edit?filter_count=7&url=https%3A//docs.google.com/spreadsheets/d/1Z4YWDKWnrSJPcyFEyHawRck0SrXg6R0hBriH7gBZuqA/pub%3Fgid%3D0%26single%3Dtrue%26output%3Dcsv&strip-headers=on&format=html&filter01=cut&cut-include-tags01=%23adm3%2Bcode%2C%23reached%2Bhouseholds%2C%23activity%2Bdescription&cut-exclude-tags01=&filter02=count&count-tags02=%23adm3%2Bcode%2C%23activity%2Bdescription&count-aggregate-tag02=%23reached%2Bhouseholds&filter03=&filter04=&filter05=&filter06=&filter07=&force=1

**Comment by davidmegginson** [comment]
Waiting for feedback from @SimonbJohnson before rolling out library changes to prod and closing this issue.

**Comment by SimonbJohnson** [comment]
Working very fast my side!

**Comment by davidmegginson** [comment]
Rolled out new libhxl to prod.  Now rebuilds query in ~2.5 seconds for 5,000-row input.  Closing.
