### ISSUE TITLE
A merge dependent on a column from previous merge not working

### ISSUE THREAD

**Issue by SimonbJohnson** [HXLStandard/hxl-proxy#61]

**Comment by davidmegginson** [comment]
Using this dataset for testing: https://docs.google.com/spreadsheets/d/12m6ugRyXDmczxiyOhn_6lhxreyyJ8iu_w0OuPFAGrl0/edit

1. Start with this tab as the base dataset: https://docs.google.com/spreadsheets/d/12m6ugRyXDmczxiyOhn_6lhxreyyJ8iu_w0OuPFAGrl0/edit#gid=0
2. Merge with this tab on ``#adm1+name``, bringing in ``#adm1+code``: https://docs.google.com/spreadsheets/d/12m6ugRyXDmczxiyOhn_6lhxreyyJ8iu_w0OuPFAGrl0/edit#gid=1567686579
3. Merge with this tab on ``#adm1+code``, bringing in ``#adm1+population``: https://docs.google.com/spreadsheets/d/12m6ugRyXDmczxiyOhn_6lhxreyyJ8iu_w0OuPFAGrl0/edit#gid=2085641078

The result should have five columns, all filled in.  Currently, the second merge is failing, as Simon reported: http://proxy.hxlstandard.org/data/edit?filter_count=7&url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F12m6ugRyXDmczxiyOhn_6lhxreyyJ8iu_w0OuPFAGrl0%2Fedit%23gid%3D0&format=html&filter01=merge&merge-url01=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F12m6ugRyXDmczxiyOhn_6lhxreyyJ8iu_w0OuPFAGrl0%2Fedit%23gid%3D1567686579&merge-tags01=adm1%2Bcode&merge-keys01=adm1%2Bname&filter02=merge&merge-url02=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F12m6ugRyXDmczxiyOhn_6lhxreyyJ8iu_w0OuPFAGrl0%2Fedit%23gid%3D2085641078&merge-tags02=population&merge-keys02=adm1%2Bcode&filter03=&filter04=&filter05=&filter06=&filter07=

**Comment by davidmegginson** [comment]
This is working with the libhxl command-line tools, so the problem seems to be specific to the HXL Proxy:

```
david@snape:~$ hxlclean 'https://docs.google.com/spreadsheets/d/12m6ugRyXDmczxiyOhn_6lhxreyyJ8iu_w0OuPFAGrl0/edit#gid=0' | hxlmerge -m 'https://docs.google.com/spreadsheets/d/12m6ugRyXDmczxiyOhn_6lhxreyyJ8iu_w0OuPFAGrl0/edit#gid=1567686579' -k adm1+name -t adm1+code | hxlmerge -m 'https://docs.google.com/spreadsheets/d/12m6ugRyXDmczxiyOhn_6lhxreyyJ8iu_w0OuPFAGrl0/edit#gid=2085641078' -k adm1+code -t population
Organisation,Cluster,Province,P-code,Population
#org+name,#sector+name,#adm1+name,#adm1+code,#population
UNICEF,WASH,Coast,P001,100000
MSF,Health,Mountains,P002,150000
Save the Children,Education,Mountains,P002,150000
Oxfam,Food Security,Plains,P003,75000
```

**Comment by davidmegginson** [comment]
Upon further investigation, this _is_ a problem with libhxl — it's not triggered by the command-line scripts because filters aren't chained.

Now being handled in https://github.com/HXLStandard/libhxl-python/issues/48

**Comment by davidmegginson** [comment]
Fixed the bug in with https://github.com/HXLStandard/libhxl-python/commit/d2decba4ba0f395d9cfb23efcb30533767cdbe31 and deployed updated library to the HXL Proxy.

The test URL now works: http://proxy.hxlstandard.org/data/edit?filter_count=7&url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F12m6ugRyXDmczxiyOhn_6lhxreyyJ8iu_w0OuPFAGrl0%2Fedit%23gid%3D0&format=html&filter01=merge&merge-url01=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F12m6ugRyXDmczxiyOhn_6lhxreyyJ8iu_w0OuPFAGrl0%2Fedit%23gid%3D1567686579&merge-tags01=adm1%2Bcode&merge-keys01=adm1%2Bname&filter02=merge&merge-url02=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F12m6ugRyXDmczxiyOhn_6lhxreyyJ8iu_w0OuPFAGrl0%2Fedit%23gid%3D2085641078&merge-tags02=population&merge-keys02=adm1%2Bcode&filter03=&filter04=&filter05=&filter06=&filter07=

**Comment by davidmegginson** [comment]
[11:56:20 AM] David Megginson: Are you still seeing #61, then?  I thought it was fixed (wrongly, I guess).
[11:56:30 AM] Simon Johnson: Yes
[11:56:41 AM] Simon Johnson: quickly find the example
[11:57:02 AM] Simon Johnson: https://docs.google.com/spreadsheets/d/1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ/edit#gid=0
[11:57:47 AM] Simon Johnson: From the American tab I removed the pcodes as seen in the other tabs.  When I run through the double merge, american pcodes for adm. Are missing
[11:58:06 AM] Simon Johnson: http://beta.proxy.hxlstandard.org/data/edit?filter_count=7&url=https://docs.google.com/spreadsheets/d/1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ/pub?gid=0&single=true&output=csv&format=html&filter01=append&append-dataset01-01=https://docs.google.com/spreadsheets/d/1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ/pub?gid=2025316943&single=true&output=csv&append-dataset01-02=https://docs.google.com/spreadsheets/d/1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ/pub?gid=289633126&single=true&output=csv&append-dataset01-03=https://docs.google.com/spreadsheets/d/1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ/pub?gid=1577071742&single=true&output=csv&append-dataset01-04=https://docs.google.com/spreadsheets/d/1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ/pub?gid=1757380963&single=true&output=csv&append-dataset01-05=https://docs.google.com/spreadsheets/d/1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ/pub?gid=2032482261&single=true&output=csv&append-dataset01-06=https://docs.google.com/spreadsheets/d/1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ/pub?gid=1219970958&single=true&output=csv&append-dataset01-07=https://docs.google.com/spreadsheets/d/1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ/pub?gid=1605708018&single=true&output=csv&append-dataset01-08=https://docs.google.com/spreadsheets/d/1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ/pub?gid=988610351&single=true&output=csv&append-dataset01-09=https://docs.google.com/spreadsheets/d/1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ/pub?gid=385073609&single=true&output=csv&filter02=replace-map&replace-map-url02=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1S9umNUolP-u_R7FYNOdHZM-g8PUcAC1xq7Y8-48bArg%2Fpub%3Fgid%3D1267882078%26single%3Dtrue%26output%3Dcsv&filter03=merge&merge-url03=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1S9umNUolP-u_R7FYNOdHZM-g8PUcAC1xq7Y8-48bArg%2Fpub%3Fgid%3D0%26single%3Dtrue%26output%3Dcsv&merge-tags03=meta%2Bid%2Cadm3%2Bcode%2Cindicator%2Bpriority&merge-keys03=adm3%2Bname&filter04=merge&merge-url04=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1S9umNUolP-u_R7FYNOdHZM-g8PUcAC1xq7Y8-48bArg%2Fpub%3Fgid%3D1687445680%26single%3Dtrue%26output%3Dcsv&merge-tags04=adm4%2Bcode&merge-keys04=adm3%2Bcode%2Cadm4%2Bname
[11:58:13 AM] Simon Johnson: HXL proxy editor for it
[11:58:19 AM] Simon Johnson: adm. codes appear for the other tags

**Comment by davidmegginson** [comment]
To help things along ...

* [Source data](https://docs.google.com/spreadsheets/d/1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ/edit#gid=0)
* [Before merges](http://beta.proxy.hxlstandard.org/data/edit?filter_count=7&url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D0&format=html&filter01=append&append-dataset01-01=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D2025316943&append-dataset01-02=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D289633126&append-dataset01-03=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D1577071742&append-dataset01-04=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D1757380963&append-dataset01-05=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D2032482261&append-dataset01-06=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D1219970958&append-dataset01-07=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D1605708018&append-dataset01-08=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D988610351&append-dataset01-09=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D385073609&append-dataset01-10=&filter02=replace-map&replace-map-url02=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1S9umNUolP-u_R7FYNOdHZM-g8PUcAC1xq7Y8-48bArg%2Fpub%3Fgid%3D1267882078%26single%3Dtrue%26output%3Dcsv&filter03=&filter04=&filter05=&filter06=&filter07=)
* [After first merge](http://beta.proxy.hxlstandard.org/data/edit?filter_count=7&url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D0&format=html&filter01=append&append-dataset01-01=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D2025316943&append-dataset01-02=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D289633126&append-dataset01-03=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D1577071742&append-dataset01-04=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D1757380963&append-dataset01-05=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D2032482261&append-dataset01-06=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D1219970958&append-dataset01-07=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D1605708018&append-dataset01-08=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D988610351&append-dataset01-09=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D385073609&append-dataset01-10=&filter02=replace-map&replace-map-url02=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1S9umNUolP-u_R7FYNOdHZM-g8PUcAC1xq7Y8-48bArg%2Fpub%3Fgid%3D1267882078%26single%3Dtrue%26output%3Dcsv&filter03=merge&merge-url03=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1S9umNUolP-u_R7FYNOdHZM-g8PUcAC1xq7Y8-48bArg%2Fpub%3Fgid%3D0%26single%3Dtrue%26output%3Dcsv&merge-tags03=meta%2Bid%2Cadm3%2Bcode%2Cindicator%2Bpriority&merge-keys03=adm3%2Bname&filter04=&filter05=&filter06=&filter07=)
* [After second merge](http://beta.proxy.hxlstandard.org/data/edit?filter_count=7&url=https://docs.google.com/spreadsheets/d/1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ/pub?gid=0&single=true&output=csv&format=html&filter01=append&append-dataset01-01=https://docs.google.com/spreadsheets/d/1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ/pub?gid=2025316943&single=true&output=csv&append-dataset01-02=https://docs.google.com/spreadsheets/d/1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ/pub?gid=289633126&single=true&output=csv&append-dataset01-03=https://docs.google.com/spreadsheets/d/1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ/pub?gid=1577071742&single=true&output=csv&append-dataset01-04=https://docs.google.com/spreadsheets/d/1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ/pub?gid=1757380963&single=true&output=csv&append-dataset01-05=https://docs.google.com/spreadsheets/d/1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ/pub?gid=2032482261&single=true&output=csv&append-dataset01-06=https://docs.google.com/spreadsheets/d/1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ/pub?gid=1219970958&single=true&output=csv&append-dataset01-07=https://docs.google.com/spreadsheets/d/1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ/pub?gid=1605708018&single=true&output=csv&append-dataset01-08=https://docs.google.com/spreadsheets/d/1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ/pub?gid=988610351&single=true&output=csv&append-dataset01-09=https://docs.google.com/spreadsheets/d/1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ/pub?gid=385073609&single=true&output=csv&filter02=replace-map&replace-map-url02=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1S9umNUolP-u_R7FYNOdHZM-g8PUcAC1xq7Y8-48bArg%2Fpub%3Fgid%3D1267882078%26single%3Dtrue%26output%3Dcsv&filter03=merge&merge-url03=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1S9umNUolP-u_R7FYNOdHZM-g8PUcAC1xq7Y8-48bArg%2Fpub%3Fgid%3D0%26single%3Dtrue%26output%3Dcsv&merge-tags03=meta%2Bid%2Cadm3%2Bcode%2Cindicator%2Bpriority&merge-keys03=adm3%2Bname&filter04=merge&merge-url04=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1S9umNUolP-u_R7FYNOdHZM-g8PUcAC1xq7Y8-48bArg%2Fpub%3Fgid%3D1687445680%26single%3Dtrue%26output%3Dcsv&merge-tags04=adm4%2Bcode&merge-keys04=adm3%2Bcode%2Cadm4%2Bname)

**Comment by davidmegginson** [comment]
The problem was that the original template had blank columns already for the merge keys, but the merge was creating new columns; that meant that the second merge saw only blank values for adm3+code and adm4+name.

While the merge filter in the HXL library has always had support for overwriting existing columns, that wasn't exposed through the HXL Proxy UI until a few days ago.  I changed the above merge, checking the "Use existing empty cells where possible" box for both merges, and it now looks like it's working properly: [new filter chain](http://beta.proxy.hxlstandard.org/data/edit?filter_count=7&url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D0&format=html&filter01=append&append-dataset01-01=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D2025316943&append-dataset01-02=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D289633126&append-dataset01-03=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D1577071742&append-dataset01-04=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D1757380963&append-dataset01-05=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D2032482261&append-dataset01-06=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D1219970958&append-dataset01-07=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D1605708018&append-dataset01-08=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D988610351&append-dataset01-09=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D385073609&append-dataset01-10=&filter02=replace-map&replace-map-url02=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1S9umNUolP-u_R7FYNOdHZM-g8PUcAC1xq7Y8-48bArg%2Fpub%3Fgid%3D1267882078%26single%3Dtrue%26output%3Dcsv&filter03=merge&merge-url03=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1S9umNUolP-u_R7FYNOdHZM-g8PUcAC1xq7Y8-48bArg%2Fpub%3Fgid%3D0%26single%3Dtrue%26output%3Dcsv&merge-tags03=meta%2Bid%2Cadm3%2Bcode%2Cindicator%2Bpriority&merge-keys03=adm3%2Bname&merge-replace03=on&filter04=merge&merge-url04=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1S9umNUolP-u_R7FYNOdHZM-g8PUcAC1xq7Y8-48bArg%2Fpub%3Fgid%3D1687445680%26single%3Dtrue%26output%3Dcsv&merge-tags04=adm4%2Bcode&merge-keys04=adm3%2Bcode%2Cadm4%2Bname&merge-replace04=on&filter05=&filter06=&filter07=)

I do see a value "None" in the adm4+code column, however, and will investigate it in https://github.com/HXLStandard/libhxl-python/issues/52  I've also create an issue to use the first _non-empty_ value for merging: https://github.com/HXLStandard/libhxl-python/issues/53

@SimonbJohnson can you confirm that this modified filter chain is working properly (aside from the "None" value)?

**Comment by davidmegginson** [comment]
Corrected URL for the full (working) merge: http://beta.proxy.hxlstandard.org/data/edit?filter_count=7&url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D0&format=html&filter01=append&append-dataset01-01=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D2025316943&append-dataset01-02=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D289633126&append-dataset01-03=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D1577071742&append-dataset01-04=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D1757380963&append-dataset01-05=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D2032482261&append-dataset01-06=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D1219970958&append-dataset01-07=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D1605708018&append-dataset01-08=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D988610351&append-dataset01-09=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1s2LBGJyy9OfmB55BOjy5N2o0VivSDu7yCRqiMlxATOQ%2Fpub%3Fgid%3D385073609&append-dataset01-10=&filter02=replace-map&replace-map-url02=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1S9umNUolP-u_R7FYNOdHZM-g8PUcAC1xq7Y8-48bArg%2Fpub%3Fgid%3D1267882078%26single%3Dtrue%26output%3Dcsv&filter03=merge&merge-url03=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1S9umNUolP-u_R7FYNOdHZM-g8PUcAC1xq7Y8-48bArg%2Fpub%3Fgid%3D0%26single%3Dtrue%26output%3Dcsv&merge-tags03=meta%2Bid%2Cadm3%2Bcode%2Cindicator%2Bpriority&merge-keys03=adm3%2Bname&merge-replace03=on&filter04=merge&merge-url04=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1S9umNUolP-u_R7FYNOdHZM-g8PUcAC1xq7Y8-48bArg%2Fpub%3Fgid%3D1687445680%26single%3Dtrue%26output%3Dcsv&merge-tags04=adm4%2Bcode&merge-keys04=adm3%2Bcode%2Cadm4%2Bname&merge-replace04=on&filter05=&filter06=&filter07=

**Comment by davidmegginson** [comment]
Fixed https://github.com/HXLStandard/libhxl-python/issues/52 which was causing "None" to appear as a merged value.

**Comment by davidmegginson** [comment]
No further bug reports, so assuming it's now resolved.
