### ISSUE TITLE
Tag non-hxl result in error

### ISSUE THREAD

**Issue by SimonbJohnson** [HXLStandard/hxl-proxy#68]
HXL Proxy
Error
Unknown filter type 'tagger'

**Comment by davidmegginson** [comment]
Also, there is no way right now to use the UI to set up the tagger.

**Comment by davidmegginson** [comment]
Confirmed working now: [test link](http://proxy.hxlstandard.org/data/edit?filter_count=7&url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1yS6GTU2H4jDPZ5Rr7Z1cHC7Qke_VzFvcjxHVChmeHHo%2Fedit%23gid%3D1101521524&format=html&filter01=tagger&tagger-01-header=sector%2Fcluster&tagger-01-tag=%23sector&tagger-02-header=subsector&tagger-02-tag=%23subsector&tagger-03-header=organizaci%C3%B3n&tagger-03-tag=%23org&tagger-04-header=&tagger-04-tag=&tagger-05-header=&tagger-05-tag=&tagger-06-header=&tagger-06-tag=&tagger-07-header=&tagger-07-tag=&tagger-08-header=&tagger-08-tag=&tagger-09-header=&tagger-09-tag=&tagger-10-header=&tagger-10-tag=&filter02=&filter03=&filter04=&filter05=&filter06=&filter07=)
