### ISSUE TITLE
Tagger crashing on Google sheet

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/hxl-proxy#73]
Reported by @python-b5:

http://beta.proxy.hxlstandard.org/data/tagger?url=https%3A//docs.google.com/spreadsheets/d/1-LypnJPLbPFJ0tK54zJlkewK1s7NM1YQzraSdGa6tYU/edit%3Fusp%3Ddrive_web

**Comment by davidmegginson** [comment]
Trying to access a Google Sheet that no longer exists: https://docs.google.com/spreadsheets/d/1-LypnJPLbPFJ0tK54zJlkewK1s7NM1/edit

Will need to show a more-useful error message.

**Comment by python-b5** [comment]
The document exists all right

**Comment by davidmegginson** [comment]
Added better error handling to let the user know what's going on, and provide a link for GitHub bug reports. See 741211e3536ded83dcd10c7219aacf82e9731be6
