### ISSUE TITLE
URL generated incorrectely

### ISSUE THREAD

**Issue by SimonbJohnson** [HXLStandard/hxl-proxy#76]
I added a merge column and then decided to use a replace and then a merge

The old merge was still included in the URL

http://proxy.hxlstandard.org/data?filter01=replace-map&replace-map-url01=https%3A//docs.google.com/spreadsheets/d/12TdWAO9BmavBkGEM-7hPV7IMjN_EOJY_2iGnW_ezjuk/pub%3Foutput%3Dcsv&filter02=merge&merge-url02=https%3A//docs.google.com/spreadsheets/d/12TdWAO9BmavBkGEM-7hPV7IMjN_EOJY_2iGnW_ezjuk/pub%3Foutput%3Dcsv&merge-tags02=%23country%2Bcode&merge-keys02=%23country-code&filter03=&filter04=&filter05=&filter06=&filter07=&force=on&merge-url01=https%3A//docs.google.com/spreadsheets/d/12TdWAO9BmavBkGEM-7hPV7IMjN_EOJY_2iGnW_ezjuk/pub%3Foutput%3Dcsv&merge-tags01=%23country%2Bcode&merge-keys01=%23country-code&filter_count=7&url=https%3A//docs.google.com/spreadsheets/d/1m3XUjtbLWKEUpUKu4ic16ruDeNj7yuZG2_1Y8U-tvs0/pub%3Fgid%3D0%26single%3Dtrue%26output%3Dcsv&format=html

**Comment by davidmegginson** [comment]
The parameters will be ignored because the value of _filter01_ is not "merge", but they still make things a bit ugly.  They're being included right now because the forms try to preserve any extra GET parameters, but they need to be smart about excluding old filter parameters.
