### ISSUE TITLE
Cross-domain error after redirect from http to https

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/hxl-proxy#84]
As reported by @SimonbJohnson if a browser-based client makes an XHR request for the http version of the HXL Proxy rather than the https version, it ends up throwing a cross-domain error.  I'm not sure why that's happening, because the https URL that it's redirecting to will include the Access-Control-Allow-Origin: * header.

Do we need to add "Access-Control-Allow-Origin: *" to the redirect as well, or is it simply a matter of making sure that people know to use the https URLs in future browser-based visualisations?

**Comment by teodorescuserban** [comment]
Uhm.. It looks like the cors header is being passed already. I added just for the fun of it ```*.org``` and ```simonbjohnson.github.io```

![cors-on-proxy-hxl](https://cloud.githubusercontent.com/assets/1542984/11017588/a850ca28-85ac-11e5-8e71-5abd507dd837.png)

**Comment by teodorescuserban** [comment]
Will see how would we add cors to redirect.

**Comment by SimonbJohnson** [comment]
Getting this error now about multiple values on https

XMLHttpRequest cannot load https://proxy.hxlstandard.org/data.json?filter_count=7&url=https%3A//www.dr…ter01=&filter02=&filter03=&filter04=&filter05=&filter06=&filter07=&force=1. The 'Access-Control-Allow-Origin' header contains multiple values '*, *.org, simonbjohnson.github.io', but only one is allowed. Origin 'http://simonbjohnson.github.io' is therefore not allowed access.

**Comment by teodorescuserban** [comment]
Yes, I'll fix it...

Lun, 9 nov. 2015, 12:27, SimonbJohnson <notifications@github.com> a scris:

**Comment by teodorescuserban** [comment]
Fixed.
This still does not solve the issue with cors on redirect which seems to be more complicated than just add the cors header to the redirect.

**Comment by SimonbJohnson** [comment]
Thanks!  That's working.  I'm updating everything to https, so from my end no rush.

**Comment by teodorescuserban** [comment]
I have added the cors header to the redirect itself. 
@SimonbJohnson can you go back to http call for a bit and let me know if it works?
We should find a solution for the redirect anyway.
Thank you.

**Comment by SimonbJohnson** [comment]
@teodorescuserban it's not working.

XMLHttpRequest cannot load http://proxy.hxlstandard.org/data.json?filter_count=7&url=https%3A//docs.go…ag01=%23sector&filter02=&filter03=&filter04=&filter05=&filter06=&filter07=. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://simonbjohnson.github.io' is therefore not allowed access.

**Comment by teodorescuserban** [comment]
What is the page you are trying?
Keep it on http and give me some time please.

**Comment by SimonbJohnson** [comment]
http://simonbjohnson.github.io/nepal-eq-2015-rc-recovery-3w/
Thanks!

**Comment by teodorescuserban** [comment]
Hm Ok it seems to be working if I only add the cors header to the 301 redirect. Cool :)
@SimonbJohnson please double check if the page mentioned works now on http and close the ticket.

**Comment by SimonbJohnson** [comment]
@teodorescuserban Working smoothly!  Thanks for the fast work. @davidmegginson can you close?

**Comment by teodorescuserban** [comment]
Thank you for help @SimonbJohnson !

**Comment by davidmegginson** [comment]
Just to confirm, allowed origin must always be "*" (I can't check right
now).

**Comment by teodorescuserban** [comment]
Nginx only add this for the redirect.
The https is getting it from app.
So yep, it looks like always.

Lun, 9 nov. 2015, 18:36, David Megginson <notifications@github.com> a scris:

**Comment by davidmegginson** [comment]
Thanks, everyone. Closing.
