### ISSUE TITLE
Redirects go to beta-proxy

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/hxl-proxy#88]
Session cookies are not getting through with beta.proxy.  Here's how to reproduce:

1. Set up Chrome with dev tools visible, showing Resources/Cookies displayed.
2. Go to https://proxy.hxlstandard.org/data/edit?url=https%3A%2F%2Fdocs.google.com%2Fa%2Fmegginson.com%2Fspreadsheets%2Fd%2F1ytPD-f4a8CbNKTfMS3EqZOpBo9LWCk_NDKxJCgmpXA8%2Fedit%3Fusp%3Ddrive_web -- you will see that no cookies are set.
3. Select "Actions/Save this view" and save the view (any name/any password) -- you will see that a cookie named "session" appears for the site.
4. Repeat steps 2–3 for https://beta.proxy.hxlstandard.org/data/edit?url=https%3A%2F%2Fdocs.google.com%2Fa%2Fmegginson.com%2Fspreadsheets%2Fd%2F1ytPD-f4a8CbNKTfMS3EqZOpBo9LWCk_NDKxJCgmpXA8%2Fedit%3Fusp%3Ddrive_web -- this time, you will see that no cookie appears.

**Comment by davidmegginson** [comment]
It looks like it's the old redirect problem.  When you submit the form, it changes from beta.proxy.hxlstandard.org to beta-proxy.hxlstandard.org. That's why the cookie vanishes.

**Comment by teodorescuserban** [comment]
Can you use beta-proxy in the first place?

**Comment by davidmegginson** [comment]
I'll give it a try. I need to change the authorisations in Dropbox, Google
Drive, and Humanitarian.ID first, so that they'll accept it as an origin.

**Comment by teodorescuserban** [comment]
I can revert tomorriw the name order so that beta-proxy will be forced to beta.proxy until you get the chance to solve all above.
You would needed to do it anyway because of the ssl, right?

**Comment by davidmegginson** [comment]
That would be great, thanks.  I bought the kind of cert where I can list a
few different domain names, so beta.proxy works with SSL as well, but I
suspect we'll end up with beta-proxy eventually.

**Comment by teodorescuserban** [comment]
Sorry for delay.
Now it should work for beta.proxy

**Comment by davidmegginson** [comment]
It's mostly working, except when I do a redirect (e.g. to "/") -- then I end up at beta-proxy again.  I've tested after clearing my cache and restarting the browser, and also in incognito mode.

**Comment by davidmegginson** [comment]
Fixed now -- thanks, @teodorescuserban !
