### ISSUE TITLE
Validation test fails.

### ISSUE THREAD

**Issue by teodorescuserban** [HXLStandard/hxl-proxy#96]
```
======================================================================
FAIL: test_default_schema (tests.test_controllers.TestValidationPage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.5/unittest/mock.py", line 1157, in patched
    return func(*args, **keywargs)
  File "/srv/www/tests/test_controllers.py", line 201, in test_default_schema
    'url': DATASET_URL
  File "/srv/www/tests/base.py", line 49, in get
    self.assertEqual(status, self.response.status_code)
AssertionError: 200 != 500

----------------------------------------------------------------------
Ran 48 tests in 26.127s

FAILED (failures=1)
```

and then validation fails on resources - [HERE](https://liv-proxy.hdx.rwlabs.org/data/validate?tagger-41-header=1975&tagger-51-header=1965&tagger-17-header=1999&tagger-56-header=1960&tagger-28-header=1988&tagger-10-header=2006&tagger-25-header=1991&header-row=1&tagger-48-header=1968&tagger-46-header=1970&tagger-06-header=2010&tagger-53-header=1963&tagger-35-header=1981&tagger-43-header=1973&tagger-52-header=1964&tagger-22-header=1994&tagger-03-header=2013&tagger-12-header=2004&tagger-50-header=1966&tagger-30-header=1986&tagger-18-header=1998&tagger-19-header=1997&tagger-47-header=1969&tagger-33-header=1983&tagger-04-header=2012&tagger-36-header=1980&tagger-34-header=1982&tagger-24-header=1992&tagger-16-header=2000&tagger-44-header=1972&tagger-37-header=1979&tagger-40-header=1976&tagger-23-header=1993&tagger-07-header=2009&tagger-13-header=2003&tagger-05-header=2011&tagger-09-header=2007&tagger-21-header=1995&tagger-31-header=1985&tagger-49-header=1967&tagger-39-header=1977&tagger-20-header=1996&tagger-15-header=2001&tagger-08-header=2008&tagger-02-tag=%23country%2Bcode&tagger-01-tag=%23country&tagger-27-header=1989&tagger-45-header=1971&tagger-11-header=2005&tagger-02-header=country+name&tagger-42-header=1974&tagger-14-header=2002&tagger-32-header=1984&tagger-29-header=1987&tagger-38-header=1978&tagger-54-header=1962&url=https%3A//data.hdx.rwlabs.org/dataset/a4f65fc8-ffda-4d5f-baed-fb6198bbd152/resource/71de9495-e761-4295-891a-260cd75f7630&tagger-26-header=1990&tagger-01-header=country+code&tagger-55-header=1961)

**Comment by teodorescuserban** [comment]
Actually this looks like an issue with libhxl. When installing it with pip, I don't get the ```/usr/lib/python3.5/site-packages/hxl/hxl-default-schema.csv``` file.

**Comment by davidmegginson** [comment]
Interesting! I'll investigate further.

**Comment by davidmegginson** [comment]
I've added a MANIFEST.in, which should make sure that the default schema gets included. Can you test again? The version installed with pip should be 2.7.1 now.

**Comment by teodorescuserban** [comment]
Excelent. It works. Thank you!
