### ISSUE TITLE
make hxl-proxy aware of url subpaths

### ISSUE THREAD

**Issue by teodorescuserban** [HXLStandard/hxl-proxy#99]
We need sometimes to run certain apps not under the url root path, but on subpaths.

Please help us do that!

Thank you!

**Comment by davidmegginson** [comment]
I've started implementing this is a separate "subpaths" branch, but it's going to be a major change, and I'm concerned about destabilising the app (which depends a lot on URL paths for workflow). Is this a high priority for the dev team, @teodorescuserban , or could I delay the change until after mid June (and the IMPACT training in Senegal)?

**Comment by teodorescuserban** [comment]
This is just nice thing to have if possible. :)

On Fri, 29 Apr 2016, 21:27 David Megginson, <notifications@github.com>
wrote:

> I've started implementing this is a separate "subpaths" branch, but it's
> going to be a major change, and I'm concerned about destabilising the app
> (which depends a lot on URL paths for workflow). Is this a high priority
> for the dev team, @teodorescuserban <https://github.com/teodorescuserban>
> , or could I delay the change until after mid June (and the IMPACT training
> in Senegal)?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/HXLStandard/hxl-proxy/issues/99#issuecomment-215839513>
>
-- 
Serban Teodorescu
SysEngineer / DevOps

**Comment by davidmegginson** [comment]
Thanks, @teodorescuserban -- I won't make this a priority for now, then, but I'll keep the issue around.

**Comment by davidmegginson** [comment]
@teodorescuserban - with the setup you're planning, would the HXL Proxy see the subpath in the request path?  e.g. if you had it mounted under https://tools.humdata.org/proxy/, would the app see

  /proxy/data

or

  /data

as the incoming request path?

**Comment by teodorescuserban** [comment]
I can do either without too much problems, @davidmegginson , but it would be better I think to pass to the app the full path and let app decide which prefix it needs to remove; in this case I will pass `X-Script-Name` header. Ideally the app will be able to set the url subpath prefix from an environment variable.

Please see also http://flask.pocoo.org/snippets/35/

**Comment by davidmegginson** [comment]
Thanks, @teodorescuserban . I've started going over the code today to develop a subpath strategy. And just to make sure I understand, this is now a high-priority issue that potentially blocks the HXL Proxy deployment into the tools, domain (?)

**Comment by teodorescuserban** [comment]
If that works, yes. :)
In all seriousness though, we are able to serve hxlproxy (at least the .json endpoints, we dont care at this point about its UI) for tools.

**Comment by davidmegginson** [comment]
So the JSON part is already working under a subpath? If it's not critical, I'll keep working on it, but at a slightly more-relaxed pace.

**Comment by teodorescuserban** [comment]
Currently I am rewriting all request made for `/hxlproxy/data.json`, removing `/hxlproxy`.
Because the json is a simple response without links to other resources it works just fine.
But if you go to `/hxlproxy` the app will incorrectly redirect you to `/data/source` (which will throw 404 from nginx).

**Comment by davidmegginson** [comment]
Implemented in f862ef7c0bdb8592d22457351cfc52525908f36a and ready for testing.
